USE `frzk_rkb`;
SET NAMES utf8mb4;
START TRANSACTION;

/* Abschnitt 3.2.8 – vollständige Neufassung V2, idempotent
   Voraussetzung: Revision 3.2.7 ist eingespielt.
   Neue Quellen [73]–[74]. Gleichungen (3.184)–(3.211). */

SET @parent_revision_id := (SELECT `revision_id` FROM `repository_revisions` WHERE `revision_code`='RKB-2026-07-15-K3.2.7-NEUFASSUNG-V2' LIMIT 1);
INSERT INTO `repository_revisions` (`revision_code`,`revision_date`,`scope_type`,`scope_reference`,`version_label`,`summary`,`created_by`,`parent_revision_id`) VALUES
('RKB-2026-07-15-K3.2.8-NEUFASSUNG-V2',NOW(),'section','3.2.8','2.0','Neufassung von Abschnitt 3.2.8 zu Nichtlinearität, Linearisierung, lokalen Bifurkationen und emergenten Strukturwechseln.','Olaf Thiele / ChatGPT',@parent_revision_id)
ON DUPLICATE KEY UPDATE `revision_id`=LAST_INSERT_ID(`revision_id`),`revision_date`=VALUES(`revision_date`),`summary`=VALUES(`summary`),`parent_revision_id`=VALUES(`parent_revision_id`);
SET @revision_id := LAST_INSERT_ID();
SET @section_id := (SELECT `section_id` FROM `dissertation_sections` WHERE `section_code`='3.2.8' LIMIT 1);
UPDATE `dissertation_sections` SET `title`='Nichtlinearität, Bifurkationen und Emergenz als mathematische Grundlagen qualitativer Strukturveränderungen',`status`='review',`is_original_contribution`=0,`notes`='Neufassung V2 mit Quellen [73]–[74] und Gleichungen (3.184)–(3.211).',`updated_at`=NOW() WHERE `section_id`=@section_id;

/* Abschnittsartefakte kontrolliert erneuern. */
DELETE es FROM `equation_symbols` es JOIN `equations` e ON e.`equation_id`=es.`equation_id` WHERE e.`section_id`=@section_id;
DELETE FROM `equations` WHERE `section_id`=@section_id;
DELETE FROM `definitions` WHERE `section_id`=@section_id;
DELETE FROM `source_usage` WHERE `section_id`=@section_id;
DELETE FROM `symbols` WHERE `first_section_id`=@section_id AND `scope_type`='section';
DELETE FROM `section_change_log` WHERE `section_id`=@section_id AND `revision_id`=@revision_id;

/* Vorhandene Literaturziffern [73] und [74] kontrolliert ersetzen. */
SET @old_73:=(SELECT `source_id` FROM `sources` WHERE `citation_number`=73 LIMIT 1);
DELETE FROM `source_usage` WHERE `source_id`=@old_73;
DELETE FROM `annotations` WHERE `source_id`=@old_73;
DELETE FROM `source_topics` WHERE `source_id`=@old_73;
DELETE FROM `source_relations` WHERE `source_id_from`=@old_73 OR `source_id_to`=@old_73;
DELETE FROM `source_authors` WHERE `source_id`=@old_73;
DELETE FROM `sources` WHERE `source_id`=@old_73;
SET @old_74:=(SELECT `source_id` FROM `sources` WHERE `citation_number`=74 LIMIT 1);
DELETE FROM `source_usage` WHERE `source_id`=@old_74;
DELETE FROM `annotations` WHERE `source_id`=@old_74;
DELETE FROM `source_topics` WHERE `source_id`=@old_74;
DELETE FROM `source_relations` WHERE `source_id_from`=@old_74 OR `source_id_to`=@old_74;
DELETE FROM `source_authors` WHERE `source_id`=@old_74;
DELETE FROM `sources` WHERE `source_id`=@old_74;

/* Autoren. */
INSERT INTO `authors` (`family_name`,`given_names`,`normalized_name`,`birth_year`,`death_year`,`notes`) VALUES ('Kuznetsov','Yuri A.','Kuznetsov, Yuri A.',1959,NULL,'Standardreferenz der angewandten Bifurkationstheorie.') ON DUPLICATE KEY UPDATE `author_id`=LAST_INSERT_ID(`author_id`),`notes`=VALUES(`notes`);
SET @author_kuznetsov:=(SELECT `author_id` FROM `authors` WHERE `normalized_name`='Kuznetsov, Yuri A.' LIMIT 1);
INSERT INTO `authors` (`family_name`,`given_names`,`normalized_name`,`birth_year`,`death_year`,`notes`) VALUES ('Guckenheimer','John','Guckenheimer, John',1945,NULL,'Grundlegende Arbeiten zu nichtlinearen dynamischen Systemen und Bifurkationen.') ON DUPLICATE KEY UPDATE `author_id`=LAST_INSERT_ID(`author_id`),`notes`=VALUES(`notes`);
SET @author_guckenheimer:=(SELECT `author_id` FROM `authors` WHERE `normalized_name`='Guckenheimer, John' LIMIT 1);
INSERT INTO `authors` (`family_name`,`given_names`,`normalized_name`,`birth_year`,`death_year`,`notes`) VALUES ('Holmes','Philip','Holmes, Philip',1945,NULL,'Grundlegende Arbeiten zu nichtlinearen Schwingungen, Dynamik und Bifurkationen.') ON DUPLICATE KEY UPDATE `author_id`=LAST_INSERT_ID(`author_id`),`notes`=VALUES(`notes`);
SET @author_holmes:=(SELECT `author_id` FROM `authors` WHERE `normalized_name`='Holmes, Philip' LIMIT 1);

/* Neue Quellen [73] und [74]. */
INSERT INTO `sources` (`citation_number`,`source_key`,`source_type`,`title`,`year_original`,`year_edition`,`journal`,`publisher`,`place`,`volume`,`issue`,`pages`,`edition`,`language_code`,`priority`,`evidence_type`,`frzk_relevance`,`verification_status`,`first_citation_section_code`,`first_citation_note`,`full_citation_text`,`short_citation_text`,`notes`,`created_revision_id`) VALUES
(73,'kuznetsov_applied_bifurcation_theory_2004','book','Elements of Applied Bifurcation Theory',1995,2004,NULL,'Springer','New York',NULL,NULL,NULL,'3rd Edition','en',5,'reference',5,'partially_verified','3.2.8','Erstnennung in Abschnitt 3.2.8.','Kuznetsov, Yuri A.: Elements of Applied Bifurcation Theory. 3. Auflage. New York: Springer, 2004.','Kuznetsov [73]','Standardwerk zur lokalen und angewandten Bifurkationstheorie.',@revision_id)
ON DUPLICATE KEY UPDATE `source_id`=LAST_INSERT_ID(`source_id`),`source_key`=VALUES(`source_key`),`title`=VALUES(`title`),`edition`=VALUES(`edition`),`full_citation_text`=VALUES(`full_citation_text`),`verification_status`=VALUES(`verification_status`),`created_revision_id`=VALUES(`created_revision_id`);
SET @source_73_id:=LAST_INSERT_ID();
INSERT INTO `sources` (`citation_number`,`source_key`,`source_type`,`title`,`year_original`,`year_edition`,`journal`,`publisher`,`place`,`volume`,`issue`,`pages`,`language_code`,`priority`,`evidence_type`,`frzk_relevance`,`verification_status`,`first_citation_section_code`,`first_citation_note`,`full_citation_text`,`short_citation_text`,`notes`,`created_revision_id`) VALUES
(74,'guckenheimer_holmes_nonlinear_oscillations_1983','book','Nonlinear Oscillations, Dynamical Systems, and Bifurcations of Vector Fields',1983,1983,NULL,'Springer','New York',NULL,NULL,NULL,'en',5,'reference',5,'partially_verified','3.2.8','Erstnennung in Abschnitt 3.2.8.','Guckenheimer, John; Holmes, Philip: Nonlinear Oscillations, Dynamical Systems, and Bifurcations of Vector Fields. New York: Springer, 1983.','Guckenheimer/Holmes [74]','Standardwerk zu nichtlinearen Schwingungen, Bifurkationen und chaotischer Dynamik.',@revision_id)
ON DUPLICATE KEY UPDATE `source_id`=LAST_INSERT_ID(`source_id`),`source_key`=VALUES(`source_key`),`title`=VALUES(`title`),`full_citation_text`=VALUES(`full_citation_text`),`verification_status`=VALUES(`verification_status`),`created_revision_id`=VALUES(`created_revision_id`);
SET @source_74_id:=LAST_INSERT_ID();
INSERT INTO `source_authors` (`source_id`,`author_id`,`author_order`,`role`) VALUES
(@source_73_id,@author_kuznetsov,1,'author'),(@source_74_id,@author_guckenheimer,1,'author'),(@source_74_id,@author_holmes,2,'author')
ON DUPLICATE KEY UPDATE `role`=VALUES(`role`),`author_order`=VALUES(`author_order`);

/* Annotationen. */
INSERT INTO `annotations` (`source_id`,`contribution`,`significance_for_dissertation`,`citation_reason`,`adopted_claims`,`limitations`,`scientific_discussion`,`annotation_status`,`reviewed_at`) VALUES
(@source_73_id,'Systematische Klassifikation lokaler Bifurkationen und ihrer Normalformen.','Zentrale Referenz für Definitionen, kritische Parameterwerte und lokale Bifurkationstypen in 3.2.8.','Belegt die mathematische Struktur von Sattel-Knoten-, transkritischer, Pitchfork- und Hopf-Bifurkation.','Bifurkationen beschreiben qualitative Strukturänderungen parameterabhängiger Dynamik.','Schwerpunkt auf etablierter lokaler Bifurkationstheorie.','Die Quelle wird mit globalen nichtlinearen Perspektiven aus [74] ergänzt.','reviewed',NOW())
ON DUPLICATE KEY UPDATE `contribution`=VALUES(`contribution`),`significance_for_dissertation`=VALUES(`significance_for_dissertation`),`citation_reason`=VALUES(`citation_reason`),`adopted_claims`=VALUES(`adopted_claims`),`limitations`=VALUES(`limitations`),`scientific_discussion`=VALUES(`scientific_discussion`),`annotation_status`='reviewed',`reviewed_at`=NOW();
INSERT INTO `annotations` (`source_id`,`contribution`,`significance_for_dissertation`,`citation_reason`,`adopted_claims`,`limitations`,`scientific_discussion`,`annotation_status`,`reviewed_at`) VALUES
(@source_74_id,'Verbindung nichtlinearer Schwingungen, lokaler Bifurkationen und globaler dynamischer Strukturen.','Ergänzende Standardreferenz für Nichtlinearität, Linearisierung und Hopf-Dynamik.','Belegt die Rolle nichtlinearer Terme und lokaler Normalformen für qualitative Dynamikwechsel.','Nichtlinearität ermöglicht qualitative Strukturübergänge, die in linearen Systemen nicht auftreten.','Konzentriert sich auf klassische glatte dynamische Systeme.','Die emergenztheoretische Interpretation bleibt eine wissenschaftliche Einordnung des Abschnitts.','reviewed',NOW())
ON DUPLICATE KEY UPDATE `contribution`=VALUES(`contribution`),`significance_for_dissertation`=VALUES(`significance_for_dissertation`),`citation_reason`=VALUES(`citation_reason`),`adopted_claims`=VALUES(`adopted_claims`),`limitations`=VALUES(`limitations`),`scientific_discussion`=VALUES(`scientific_discussion`),`annotation_status`='reviewed',`reviewed_at`=NOW();

SET @source_69_id:=(SELECT `source_id` FROM `sources` WHERE `citation_number`=69 LIMIT 1);
SET @source_70_id:=(SELECT `source_id` FROM `sources` WHERE `citation_number`=70 LIMIT 1);
SET @source_71_id:=(SELECT `source_id` FROM `sources` WHERE `citation_number`=71 LIMIT 1);
SET @source_72_id:=(SELECT `source_id` FROM `sources` WHERE `citation_number`=72 LIMIT 1);
INSERT INTO `source_usage` (`source_id`,`section_id`,`usage_type`,`claim_summary`,`exact_location`,`is_first_mention`,`citation_checked`,`notes`,`created_revision_id`) VALUES
(@source_73_id,@section_id,'first_citation','Lokale Bifurkationstheorie, kritische Parameter und Normalformen.','Einleitung, Linearisierung und elementare Bifurkationen',1,1,'Neue Erstnennung [73].',@revision_id),
(@source_74_id,@section_id,'first_citation','Nichtlineare Schwingungen, Dynamik und Bifurkationen von Vektorfeldern.','Nichtlinearität, Hopf-Bifurkation und wissenschaftliche Einordnung',1,1,'Neue Erstnennung [74].',@revision_id),
(@source_69_id,@section_id,'background','Flüsse, Gleichgewichtspunkte und gewöhnliche Differentialgleichungen.','Mathematischer Ausgangsrahmen',0,1,'Bestehende Quelle [69].',@revision_id),
(@source_70_id,@section_id,'comparison','Stabilitätsbegriff als Voraussetzung der Analyse von Stabilitätswechseln.','Linearisierung und Eigenwertkriterien',0,1,'Bestehende Quelle [70].',@revision_id),
(@source_71_id,@section_id,'comparison','Invarianz und asymptotische Dynamik als Bezugspunkt für Strukturwechsel.','Übergang zu Attraktoren und Emergenz',0,1,'Bestehende Quelle [71].',@revision_id),
(@source_72_id,@section_id,'state_of_research','Attraktoren als asymptotische Organisationsformen vor und nach Bifurkationen.','Emergenz und Attraktorwechsel',0,1,'Bestehende Quelle [72].',@revision_id);

/* Definitionen. */
INSERT INTO `definitions` (`definition_number`,`section_id`,`title`,`definition_text`,`formal_latex`,`word_latex`,`provenance`,`source_id`,`assumptions`,`notes`,`validation_status`,`created_revision_id`) VALUES
('Def. 3.2.8.1',@section_id,'Nichtlineares dynamisches System','Ein dynamisches System ist nichtlinear, wenn sein Entwicklungsgesetz das Superpositionsprinzip nicht erfüllt.','F(\\alpha x_1+\\beta x_2,\\mu)\\neq\\alpha F(x_1,\\mu)+\\beta F(x_2,\\mu)','F(\\alpha x_1+\\beta x_2,\\mu)\\neq\\alpha F(x_1,\\mu)+\\beta F(x_2,\\mu)','literature',@source_74_id,NULL,'Neufassung 3.2.8 V2.','checked',@revision_id)
ON DUPLICATE KEY UPDATE `section_id`=VALUES(`section_id`),`title`=VALUES(`title`),`definition_text`=VALUES(`definition_text`),`formal_latex`=VALUES(`formal_latex`),`word_latex`=VALUES(`word_latex`),`provenance`=VALUES(`provenance`),`source_id`=VALUES(`source_id`),`notes`=VALUES(`notes`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
INSERT INTO `definitions` (`definition_number`,`section_id`,`title`,`definition_text`,`formal_latex`,`word_latex`,`provenance`,`source_id`,`assumptions`,`notes`,`validation_status`,`created_revision_id`) VALUES
('Def. 3.2.8.2',@section_id,'Kontrollparameter','Ein Kontrollparameter ist eine äußere oder innere Modellgröße, deren Variation die qualitative Dynamik verändern kann.','\\mu\\in\\mathbb{R}^p','\\mu\\in\\mathbb{R}^p','literature',@source_73_id,NULL,'Neufassung 3.2.8 V2.','checked',@revision_id)
ON DUPLICATE KEY UPDATE `section_id`=VALUES(`section_id`),`title`=VALUES(`title`),`definition_text`=VALUES(`definition_text`),`formal_latex`=VALUES(`formal_latex`),`word_latex`=VALUES(`word_latex`),`provenance`=VALUES(`provenance`),`source_id`=VALUES(`source_id`),`notes`=VALUES(`notes`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
INSERT INTO `definitions` (`definition_number`,`section_id`,`title`,`definition_text`,`formal_latex`,`word_latex`,`provenance`,`source_id`,`assumptions`,`notes`,`validation_status`,`created_revision_id`) VALUES
('Def. 3.2.8.3',@section_id,'Linearisierung','Die Linearisierung ist die Approximation eines nichtlinearen Systems durch die erste Ableitung seines Vektorfeldes in der Umgebung eines Gleichgewichtspunktes.','\\dot{\\xi}=J(x^\\ast,\\mu)\\xi','\\dot{\\xi}=J(x^\\ast,\\mu)\\xi','literature',@source_73_id,NULL,'Neufassung 3.2.8 V2.','checked',@revision_id)
ON DUPLICATE KEY UPDATE `section_id`=VALUES(`section_id`),`title`=VALUES(`title`),`definition_text`=VALUES(`definition_text`),`formal_latex`=VALUES(`formal_latex`),`word_latex`=VALUES(`word_latex`),`provenance`=VALUES(`provenance`),`source_id`=VALUES(`source_id`),`notes`=VALUES(`notes`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
INSERT INTO `definitions` (`definition_number`,`section_id`,`title`,`definition_text`,`formal_latex`,`word_latex`,`provenance`,`source_id`,`assumptions`,`notes`,`validation_status`,`created_revision_id`) VALUES
('Def. 3.2.8.4',@section_id,'Jacobi-Matrix','Die Jacobi-Matrix ist die Ableitung des Vektorfeldes bezüglich der Zustandsvariablen.','J(x^\\ast,\\mu)=D_xF(x^\\ast,\\mu)','J(x^\\ast,\\mu)=D_xF(x^\\ast,\\mu)','literature',@source_73_id,NULL,'Neufassung 3.2.8 V2.','checked',@revision_id)
ON DUPLICATE KEY UPDATE `section_id`=VALUES(`section_id`),`title`=VALUES(`title`),`definition_text`=VALUES(`definition_text`),`formal_latex`=VALUES(`formal_latex`),`word_latex`=VALUES(`word_latex`),`provenance`=VALUES(`provenance`),`source_id`=VALUES(`source_id`),`notes`=VALUES(`notes`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
INSERT INTO `definitions` (`definition_number`,`section_id`,`title`,`definition_text`,`formal_latex`,`word_latex`,`provenance`,`source_id`,`assumptions`,`notes`,`validation_status`,`created_revision_id`) VALUES
('Def. 3.2.8.5',@section_id,'Kritischer Parameterwert','Ein Parameterwert ist kritisch, wenn mindestens ein Eigenwert der linearisierten Dynamik einen verschwindenden Realteil besitzt.','\\exists i:\\operatorname{Re}(\\lambda_i(\\mu_c))=0','\\exists i:\\operatorname{Re}(\\lambda_i(\\mu_c))=0','literature',@source_73_id,NULL,'Neufassung 3.2.8 V2.','checked',@revision_id)
ON DUPLICATE KEY UPDATE `section_id`=VALUES(`section_id`),`title`=VALUES(`title`),`definition_text`=VALUES(`definition_text`),`formal_latex`=VALUES(`formal_latex`),`word_latex`=VALUES(`word_latex`),`provenance`=VALUES(`provenance`),`source_id`=VALUES(`source_id`),`notes`=VALUES(`notes`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
INSERT INTO `definitions` (`definition_number`,`section_id`,`title`,`definition_text`,`formal_latex`,`word_latex`,`provenance`,`source_id`,`assumptions`,`notes`,`validation_status`,`created_revision_id`) VALUES
('Def. 3.2.8.6',@section_id,'Bifurkation','Eine Bifurkation ist eine qualitative Änderung der Dynamik bei Variation eines Parameters, sodass die Systeme beiderseits des kritischen Wertes nicht topologisch äquivalent sind.','\\Phi_{\\mu_c-\\varepsilon}\\not\\sim\\Phi_{\\mu_c+\\varepsilon}','\\Phi_{\\mu_c-\\varepsilon}\\not\\sim\\Phi_{\\mu_c+\\varepsilon}','literature',@source_73_id,NULL,'Neufassung 3.2.8 V2.','checked',@revision_id)
ON DUPLICATE KEY UPDATE `section_id`=VALUES(`section_id`),`title`=VALUES(`title`),`definition_text`=VALUES(`definition_text`),`formal_latex`=VALUES(`formal_latex`),`word_latex`=VALUES(`word_latex`),`provenance`=VALUES(`provenance`),`source_id`=VALUES(`source_id`),`notes`=VALUES(`notes`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
INSERT INTO `definitions` (`definition_number`,`section_id`,`title`,`definition_text`,`formal_latex`,`word_latex`,`provenance`,`source_id`,`assumptions`,`notes`,`validation_status`,`created_revision_id`) VALUES
('Def. 3.2.8.7',@section_id,'Sattel-Knoten-Bifurkation','Eine Sattel-Knoten-Bifurkation erzeugt oder vernichtet lokal zwei Gleichgewichtspunkte.','\\dot{x}=\\mu-x^2','\\dot{x}=\\mu-x^2','literature',@source_73_id,NULL,'Neufassung 3.2.8 V2.','checked',@revision_id)
ON DUPLICATE KEY UPDATE `section_id`=VALUES(`section_id`),`title`=VALUES(`title`),`definition_text`=VALUES(`definition_text`),`formal_latex`=VALUES(`formal_latex`),`word_latex`=VALUES(`word_latex`),`provenance`=VALUES(`provenance`),`source_id`=VALUES(`source_id`),`notes`=VALUES(`notes`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
INSERT INTO `definitions` (`definition_number`,`section_id`,`title`,`definition_text`,`formal_latex`,`word_latex`,`provenance`,`source_id`,`assumptions`,`notes`,`validation_status`,`created_revision_id`) VALUES
('Def. 3.2.8.8',@section_id,'Transkritische Bifurkation','Bei einer transkritischen Bifurkation tauschen zwei Gleichgewichtszweige ihre Stabilität.','\\dot{x}=\\mu x-x^2','\\dot{x}=\\mu x-x^2','literature',@source_73_id,NULL,'Neufassung 3.2.8 V2.','checked',@revision_id)
ON DUPLICATE KEY UPDATE `section_id`=VALUES(`section_id`),`title`=VALUES(`title`),`definition_text`=VALUES(`definition_text`),`formal_latex`=VALUES(`formal_latex`),`word_latex`=VALUES(`word_latex`),`provenance`=VALUES(`provenance`),`source_id`=VALUES(`source_id`),`notes`=VALUES(`notes`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
INSERT INTO `definitions` (`definition_number`,`section_id`,`title`,`definition_text`,`formal_latex`,`word_latex`,`provenance`,`source_id`,`assumptions`,`notes`,`validation_status`,`created_revision_id`) VALUES
('Def. 3.2.8.9',@section_id,'Pitchfork-Bifurkation','Eine Pitchfork-Bifurkation beschreibt die symmetrische Aufspaltung eines Gleichgewichtszweiges.','\\dot{x}=\\mu x-x^3','\\dot{x}=\\mu x-x^3','literature',@source_73_id,NULL,'Neufassung 3.2.8 V2.','checked',@revision_id)
ON DUPLICATE KEY UPDATE `section_id`=VALUES(`section_id`),`title`=VALUES(`title`),`definition_text`=VALUES(`definition_text`),`formal_latex`=VALUES(`formal_latex`),`word_latex`=VALUES(`word_latex`),`provenance`=VALUES(`provenance`),`source_id`=VALUES(`source_id`),`notes`=VALUES(`notes`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
INSERT INTO `definitions` (`definition_number`,`section_id`,`title`,`definition_text`,`formal_latex`,`word_latex`,`provenance`,`source_id`,`assumptions`,`notes`,`validation_status`,`created_revision_id`) VALUES
('Def. 3.2.8.10',@section_id,'Hopf-Bifurkation','Eine Hopf-Bifurkation ist ein Übergang von einem Gleichgewicht zu einer periodischen Lösung durch ein komplex konjugiertes Eigenwertpaar.','\\dot{z}=(\\mu+i\\omega)z-|z|^2z','\\dot{z}=(\\mu+i\\omega)z-|z|^2z','literature',@source_74_id,NULL,'Neufassung 3.2.8 V2.','checked',@revision_id)
ON DUPLICATE KEY UPDATE `section_id`=VALUES(`section_id`),`title`=VALUES(`title`),`definition_text`=VALUES(`definition_text`),`formal_latex`=VALUES(`formal_latex`),`word_latex`=VALUES(`word_latex`),`provenance`=VALUES(`provenance`),`source_id`=VALUES(`source_id`),`notes`=VALUES(`notes`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
INSERT INTO `definitions` (`definition_number`,`section_id`,`title`,`definition_text`,`formal_latex`,`word_latex`,`provenance`,`source_id`,`assumptions`,`notes`,`validation_status`,`created_revision_id`) VALUES
('Def. 3.2.8.11',@section_id,'Emergenter Strukturwechsel','Ein emergenter Strukturwechsel liegt vor, wenn durch eine Parameteränderung eine qualitativ neue asymptotische Organisationsform entsteht.','A(\\mu^-)\\neq A(\\mu^+)','A(\\mu^-)\\neq A(\\mu^+)','literature',@source_72_id,NULL,'Neufassung 3.2.8 V2.','checked',@revision_id)
ON DUPLICATE KEY UPDATE `section_id`=VALUES(`section_id`),`title`=VALUES(`title`),`definition_text`=VALUES(`definition_text`),`formal_latex`=VALUES(`formal_latex`),`word_latex`=VALUES(`word_latex`),`provenance`=VALUES(`provenance`),`source_id`=VALUES(`source_id`),`notes`=VALUES(`notes`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);

/* Gleichungen. */
INSERT INTO `equations` (`equation_number`,`section_id`,`title`,`equation_latex`,`word_latex`,`plain_description`,`equation_type`,`provenance`,`source_id`,`derivation`,`assumptions`,`validation_status`,`created_revision_id`) VALUES
('3.184',@section_id,'Parameterabhängiges nichtlineares System','\\dot{x}=F(x,\\mu)','\\dot{x}=F(x,\\mu)','Allgemeines kontinuierliches dynamisches System mit Kontrollparameter.','model','literature',@source_73_id,NULL,NULL,'checked',@revision_id)
ON DUPLICATE KEY UPDATE `equation_id`=LAST_INSERT_ID(`equation_id`),`section_id`=VALUES(`section_id`),`title`=VALUES(`title`),`equation_latex`=VALUES(`equation_latex`),`word_latex`=VALUES(`word_latex`),`plain_description`=VALUES(`plain_description`),`equation_type`=VALUES(`equation_type`),`provenance`=VALUES(`provenance`),`source_id`=VALUES(`source_id`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
SET @eq_3_184:=LAST_INSERT_ID();
INSERT INTO `equations` (`equation_number`,`section_id`,`title`,`equation_latex`,`word_latex`,`plain_description`,`equation_type`,`provenance`,`source_id`,`derivation`,`assumptions`,`validation_status`,`created_revision_id`) VALUES
('3.185',@section_id,'Lineares parameterabhängiges System','\\dot{x}=A(\\mu)x','\\dot{x}=A(\\mu)x','Lineare Dynamik mit parameterabhängiger Systemmatrix.','model','literature',@source_73_id,NULL,NULL,'checked',@revision_id)
ON DUPLICATE KEY UPDATE `equation_id`=LAST_INSERT_ID(`equation_id`),`section_id`=VALUES(`section_id`),`title`=VALUES(`title`),`equation_latex`=VALUES(`equation_latex`),`word_latex`=VALUES(`word_latex`),`plain_description`=VALUES(`plain_description`),`equation_type`=VALUES(`equation_type`),`provenance`=VALUES(`provenance`),`source_id`=VALUES(`source_id`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
SET @eq_3_185:=LAST_INSERT_ID();
INSERT INTO `equations` (`equation_number`,`section_id`,`title`,`equation_latex`,`word_latex`,`plain_description`,`equation_type`,`provenance`,`source_id`,`derivation`,`assumptions`,`validation_status`,`created_revision_id`) VALUES
('3.186',@section_id,'Zerlegung in linearen und nichtlinearen Anteil','\\dot{x}=A(\\mu)x+N(x,\\mu)','\\dot{x}=A(\\mu)x+N(x,\\mu)','Darstellung eines nichtlinearen Systems als linearer Anteil plus Nichtlinearität.','model','literature',@source_74_id,NULL,NULL,'checked',@revision_id)
ON DUPLICATE KEY UPDATE `equation_id`=LAST_INSERT_ID(`equation_id`),`section_id`=VALUES(`section_id`),`title`=VALUES(`title`),`equation_latex`=VALUES(`equation_latex`),`word_latex`=VALUES(`word_latex`),`plain_description`=VALUES(`plain_description`),`equation_type`=VALUES(`equation_type`),`provenance`=VALUES(`provenance`),`source_id`=VALUES(`source_id`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
SET @eq_3_186:=LAST_INSERT_ID();
INSERT INTO `equations` (`equation_number`,`section_id`,`title`,`equation_latex`,`word_latex`,`plain_description`,`equation_type`,`provenance`,`source_id`,`derivation`,`assumptions`,`validation_status`,`created_revision_id`) VALUES
('3.187',@section_id,'Verletzung des Superpositionsprinzips','F(\\alpha x_1+\\beta x_2,\\mu)\\neq\\alpha F(x_1,\\mu)+\\beta F(x_2,\\mu)','F(\\alpha x_1+\\beta x_2,\\mu)\\neq\\alpha F(x_1,\\mu)+\\beta F(x_2,\\mu)','Kennzeichen eines nichtlinearen Entwicklungsgesetzes.','definition','literature',@source_74_id,NULL,NULL,'checked',@revision_id)
ON DUPLICATE KEY UPDATE `equation_id`=LAST_INSERT_ID(`equation_id`),`section_id`=VALUES(`section_id`),`title`=VALUES(`title`),`equation_latex`=VALUES(`equation_latex`),`word_latex`=VALUES(`word_latex`),`plain_description`=VALUES(`plain_description`),`equation_type`=VALUES(`equation_type`),`provenance`=VALUES(`provenance`),`source_id`=VALUES(`source_id`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
SET @eq_3_187:=LAST_INSERT_ID();
INSERT INTO `equations` (`equation_number`,`section_id`,`title`,`equation_latex`,`word_latex`,`plain_description`,`equation_type`,`provenance`,`source_id`,`derivation`,`assumptions`,`validation_status`,`created_revision_id`) VALUES
('3.188',@section_id,'Parameterabhängiger Gleichgewichtspunkt','F(x^\\ast,\\mu)=0','F(x^\\ast,\\mu)=0','Gleichgewichtsbedingung eines parameterabhängigen Systems.','definition','literature',@source_73_id,NULL,NULL,'checked',@revision_id)
ON DUPLICATE KEY UPDATE `equation_id`=LAST_INSERT_ID(`equation_id`),`section_id`=VALUES(`section_id`),`title`=VALUES(`title`),`equation_latex`=VALUES(`equation_latex`),`word_latex`=VALUES(`word_latex`),`plain_description`=VALUES(`plain_description`),`equation_type`=VALUES(`equation_type`),`provenance`=VALUES(`provenance`),`source_id`=VALUES(`source_id`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
SET @eq_3_188:=LAST_INSERT_ID();
INSERT INTO `equations` (`equation_number`,`section_id`,`title`,`equation_latex`,`word_latex`,`plain_description`,`equation_type`,`provenance`,`source_id`,`derivation`,`assumptions`,`validation_status`,`created_revision_id`) VALUES
('3.189',@section_id,'Gleichgewichtsverzweigung','x^\\ast=x^\\ast(\\mu)','x^\\ast=x^\\ast(\\mu)','Abhängigkeit eines Gleichgewichtspunktes vom Kontrollparameter.','model','literature',@source_73_id,NULL,NULL,'checked',@revision_id)
ON DUPLICATE KEY UPDATE `equation_id`=LAST_INSERT_ID(`equation_id`),`section_id`=VALUES(`section_id`),`title`=VALUES(`title`),`equation_latex`=VALUES(`equation_latex`),`word_latex`=VALUES(`word_latex`),`plain_description`=VALUES(`plain_description`),`equation_type`=VALUES(`equation_type`),`provenance`=VALUES(`provenance`),`source_id`=VALUES(`source_id`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
SET @eq_3_189:=LAST_INSERT_ID();
INSERT INTO `equations` (`equation_number`,`section_id`,`title`,`equation_latex`,`word_latex`,`plain_description`,`equation_type`,`provenance`,`source_id`,`derivation`,`assumptions`,`validation_status`,`created_revision_id`) VALUES
('3.190',@section_id,'Lokale Abweichung vom Gleichgewicht','\\xi=x-x^\\ast','\\xi=x-x^\\ast','Lokale Koordinate relativ zum Gleichgewichtspunkt.','definition','literature',@source_73_id,NULL,NULL,'checked',@revision_id)
ON DUPLICATE KEY UPDATE `equation_id`=LAST_INSERT_ID(`equation_id`),`section_id`=VALUES(`section_id`),`title`=VALUES(`title`),`equation_latex`=VALUES(`equation_latex`),`word_latex`=VALUES(`word_latex`),`plain_description`=VALUES(`plain_description`),`equation_type`=VALUES(`equation_type`),`provenance`=VALUES(`provenance`),`source_id`=VALUES(`source_id`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
SET @eq_3_190:=LAST_INSERT_ID();
INSERT INTO `equations` (`equation_number`,`section_id`,`title`,`equation_latex`,`word_latex`,`plain_description`,`equation_type`,`provenance`,`source_id`,`derivation`,`assumptions`,`validation_status`,`created_revision_id`) VALUES
('3.191',@section_id,'Taylorentwicklung des Vektorfeldes','F(x^\\ast+\\xi,\\mu)=F(x^\\ast,\\mu)+D_xF(x^\\ast,\\mu)\\xi+\\mathcal{O}\\!\\left(\\|\\xi\\|^2\\right)','F(x^\\ast+\\xi,\\mu)=F(x^\\ast,\\mu)+D_xF(x^\\ast,\\mu)\\xi+\\mathcal{O}\\!\\left(\\|\\xi\\|^2\\right)','Lokale Taylorentwicklung des nichtlinearen Vektorfeldes.','derived','literature',@source_73_id,NULL,NULL,'checked',@revision_id)
ON DUPLICATE KEY UPDATE `equation_id`=LAST_INSERT_ID(`equation_id`),`section_id`=VALUES(`section_id`),`title`=VALUES(`title`),`equation_latex`=VALUES(`equation_latex`),`word_latex`=VALUES(`word_latex`),`plain_description`=VALUES(`plain_description`),`equation_type`=VALUES(`equation_type`),`provenance`=VALUES(`provenance`),`source_id`=VALUES(`source_id`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
SET @eq_3_191:=LAST_INSERT_ID();
INSERT INTO `equations` (`equation_number`,`section_id`,`title`,`equation_latex`,`word_latex`,`plain_description`,`equation_type`,`provenance`,`source_id`,`derivation`,`assumptions`,`validation_status`,`created_revision_id`) VALUES
('3.192',@section_id,'Linearisierte Dynamik','\\dot{\\xi}=J(x^\\ast,\\mu)\\xi','\\dot{\\xi}=J(x^\\ast,\\mu)\\xi','Linearisierung in der Umgebung eines Gleichgewichtspunktes.','model','literature',@source_73_id,NULL,NULL,'checked',@revision_id)
ON DUPLICATE KEY UPDATE `equation_id`=LAST_INSERT_ID(`equation_id`),`section_id`=VALUES(`section_id`),`title`=VALUES(`title`),`equation_latex`=VALUES(`equation_latex`),`word_latex`=VALUES(`word_latex`),`plain_description`=VALUES(`plain_description`),`equation_type`=VALUES(`equation_type`),`provenance`=VALUES(`provenance`),`source_id`=VALUES(`source_id`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
SET @eq_3_192:=LAST_INSERT_ID();
INSERT INTO `equations` (`equation_number`,`section_id`,`title`,`equation_latex`,`word_latex`,`plain_description`,`equation_type`,`provenance`,`source_id`,`derivation`,`assumptions`,`validation_status`,`created_revision_id`) VALUES
('3.193',@section_id,'Jacobi-Matrix','J(x^\\ast,\\mu)=D_xF(x^\\ast,\\mu)','J(x^\\ast,\\mu)=D_xF(x^\\ast,\\mu)','Definition der Jacobi-Matrix des Vektorfeldes.','definition','literature',@source_73_id,NULL,NULL,'checked',@revision_id)
ON DUPLICATE KEY UPDATE `equation_id`=LAST_INSERT_ID(`equation_id`),`section_id`=VALUES(`section_id`),`title`=VALUES(`title`),`equation_latex`=VALUES(`equation_latex`),`word_latex`=VALUES(`word_latex`),`plain_description`=VALUES(`plain_description`),`equation_type`=VALUES(`equation_type`),`provenance`=VALUES(`provenance`),`source_id`=VALUES(`source_id`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
SET @eq_3_193:=LAST_INSERT_ID();
INSERT INTO `equations` (`equation_number`,`section_id`,`title`,`equation_latex`,`word_latex`,`plain_description`,`equation_type`,`provenance`,`source_id`,`derivation`,`assumptions`,`validation_status`,`created_revision_id`) VALUES
('3.194',@section_id,'Lokale asymptotische Stabilitätsbedingung','\\operatorname{Re}(\\lambda_i)<0\\qquad\\forall i','\\operatorname{Re}(\\lambda_i)<0\\qquad\\forall i','Negativer Realteil aller Eigenwerte als lokale Stabilitätsbedingung.','theorem','literature',@source_74_id,NULL,NULL,'checked',@revision_id)
ON DUPLICATE KEY UPDATE `equation_id`=LAST_INSERT_ID(`equation_id`),`section_id`=VALUES(`section_id`),`title`=VALUES(`title`),`equation_latex`=VALUES(`equation_latex`),`word_latex`=VALUES(`word_latex`),`plain_description`=VALUES(`plain_description`),`equation_type`=VALUES(`equation_type`),`provenance`=VALUES(`provenance`),`source_id`=VALUES(`source_id`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
SET @eq_3_194:=LAST_INSERT_ID();
INSERT INTO `equations` (`equation_number`,`section_id`,`title`,`equation_latex`,`word_latex`,`plain_description`,`equation_type`,`provenance`,`source_id`,`derivation`,`assumptions`,`validation_status`,`created_revision_id`) VALUES
('3.195',@section_id,'Lokale Instabilitätsbedingung','\\exists i:\\operatorname{Re}(\\lambda_i)>0','\\exists i:\\operatorname{Re}(\\lambda_i)>0','Positiver Realteil mindestens eines Eigenwertes als Instabilitätskriterium.','theorem','literature',@source_74_id,NULL,NULL,'checked',@revision_id)
ON DUPLICATE KEY UPDATE `equation_id`=LAST_INSERT_ID(`equation_id`),`section_id`=VALUES(`section_id`),`title`=VALUES(`title`),`equation_latex`=VALUES(`equation_latex`),`word_latex`=VALUES(`word_latex`),`plain_description`=VALUES(`plain_description`),`equation_type`=VALUES(`equation_type`),`provenance`=VALUES(`provenance`),`source_id`=VALUES(`source_id`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
SET @eq_3_195:=LAST_INSERT_ID();
INSERT INTO `equations` (`equation_number`,`section_id`,`title`,`equation_latex`,`word_latex`,`plain_description`,`equation_type`,`provenance`,`source_id`,`derivation`,`assumptions`,`validation_status`,`created_revision_id`) VALUES
('3.196',@section_id,'Kritischer Parameterwert','\\exists i:\\operatorname{Re}\\left(\\lambda_i(\\mu_c)\\right)=0','\\exists i:\\operatorname{Re}\\left(\\lambda_i(\\mu_c)\\right)=0','Spektrale Bedingung eines kritischen Parameterwertes.','definition','literature',@source_73_id,NULL,NULL,'checked',@revision_id)
ON DUPLICATE KEY UPDATE `equation_id`=LAST_INSERT_ID(`equation_id`),`section_id`=VALUES(`section_id`),`title`=VALUES(`title`),`equation_latex`=VALUES(`equation_latex`),`word_latex`=VALUES(`word_latex`),`plain_description`=VALUES(`plain_description`),`equation_type`=VALUES(`equation_type`),`provenance`=VALUES(`provenance`),`source_id`=VALUES(`source_id`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
SET @eq_3_196:=LAST_INSERT_ID();
INSERT INTO `equations` (`equation_number`,`section_id`,`title`,`equation_latex`,`word_latex`,`plain_description`,`equation_type`,`provenance`,`source_id`,`derivation`,`assumptions`,`validation_status`,`created_revision_id`) VALUES
('3.197',@section_id,'Qualitative Änderung der Dynamik','\\Phi_{\\mu_c-\\varepsilon}\\not\\sim\\Phi_{\\mu_c+\\varepsilon}\\qquad\\text{für hinreichend kleines }\\varepsilon>0','\\Phi_{\\mu_c-\\varepsilon}\\not\\sim\\Phi_{\\mu_c+\\varepsilon}\\qquad\\text{für hinreichend kleines }\\varepsilon>0','Nichtäquivalenz der Dynamiken beiderseits eines Bifurkationswertes.','definition','literature',@source_73_id,NULL,NULL,'checked',@revision_id)
ON DUPLICATE KEY UPDATE `equation_id`=LAST_INSERT_ID(`equation_id`),`section_id`=VALUES(`section_id`),`title`=VALUES(`title`),`equation_latex`=VALUES(`equation_latex`),`word_latex`=VALUES(`word_latex`),`plain_description`=VALUES(`plain_description`),`equation_type`=VALUES(`equation_type`),`provenance`=VALUES(`provenance`),`source_id`=VALUES(`source_id`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
SET @eq_3_197:=LAST_INSERT_ID();
INSERT INTO `equations` (`equation_number`,`section_id`,`title`,`equation_latex`,`word_latex`,`plain_description`,`equation_type`,`provenance`,`source_id`,`derivation`,`assumptions`,`validation_status`,`created_revision_id`) VALUES
('3.198',@section_id,'Normalform der Sattel-Knoten-Bifurkation','\\dot{x}=\\mu-x^2','\\dot{x}=\\mu-x^2','Normalform einer Sattel-Knoten-Bifurkation.','model','literature',@source_73_id,NULL,NULL,'checked',@revision_id)
ON DUPLICATE KEY UPDATE `equation_id`=LAST_INSERT_ID(`equation_id`),`section_id`=VALUES(`section_id`),`title`=VALUES(`title`),`equation_latex`=VALUES(`equation_latex`),`word_latex`=VALUES(`word_latex`),`plain_description`=VALUES(`plain_description`),`equation_type`=VALUES(`equation_type`),`provenance`=VALUES(`provenance`),`source_id`=VALUES(`source_id`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
SET @eq_3_198:=LAST_INSERT_ID();
INSERT INTO `equations` (`equation_number`,`section_id`,`title`,`equation_latex`,`word_latex`,`plain_description`,`equation_type`,`provenance`,`source_id`,`derivation`,`assumptions`,`validation_status`,`created_revision_id`) VALUES
('3.199',@section_id,'Gleichgewichtsbedingung der Sattel-Knoten-Bifurkation','\\mu-x^2=0','\\mu-x^2=0','Stationäre Bedingung der Sattel-Knoten-Normalform.','derived','literature',@source_73_id,NULL,NULL,'checked',@revision_id)
ON DUPLICATE KEY UPDATE `equation_id`=LAST_INSERT_ID(`equation_id`),`section_id`=VALUES(`section_id`),`title`=VALUES(`title`),`equation_latex`=VALUES(`equation_latex`),`word_latex`=VALUES(`word_latex`),`plain_description`=VALUES(`plain_description`),`equation_type`=VALUES(`equation_type`),`provenance`=VALUES(`provenance`),`source_id`=VALUES(`source_id`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
SET @eq_3_199:=LAST_INSERT_ID();
INSERT INTO `equations` (`equation_number`,`section_id`,`title`,`equation_latex`,`word_latex`,`plain_description`,`equation_type`,`provenance`,`source_id`,`derivation`,`assumptions`,`validation_status`,`created_revision_id`) VALUES
('3.200',@section_id,'Gleichgewichte der Sattel-Knoten-Bifurkation','x^\\ast=\\pm\\sqrt{\\mu}','x^\\ast=\\pm\\sqrt{\\mu}','Gleichgewichtslösungen der Sattel-Knoten-Normalform.','derived','literature',@source_73_id,NULL,NULL,'checked',@revision_id)
ON DUPLICATE KEY UPDATE `equation_id`=LAST_INSERT_ID(`equation_id`),`section_id`=VALUES(`section_id`),`title`=VALUES(`title`),`equation_latex`=VALUES(`equation_latex`),`word_latex`=VALUES(`word_latex`),`plain_description`=VALUES(`plain_description`),`equation_type`=VALUES(`equation_type`),`provenance`=VALUES(`provenance`),`source_id`=VALUES(`source_id`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
SET @eq_3_200:=LAST_INSERT_ID();
INSERT INTO `equations` (`equation_number`,`section_id`,`title`,`equation_latex`,`word_latex`,`plain_description`,`equation_type`,`provenance`,`source_id`,`derivation`,`assumptions`,`validation_status`,`created_revision_id`) VALUES
('3.201',@section_id,'Normalform der transkritischen Bifurkation','\\dot{x}=\\mu x-x^2','\\dot{x}=\\mu x-x^2','Normalform einer transkritischen Bifurkation.','model','literature',@source_73_id,NULL,NULL,'checked',@revision_id)
ON DUPLICATE KEY UPDATE `equation_id`=LAST_INSERT_ID(`equation_id`),`section_id`=VALUES(`section_id`),`title`=VALUES(`title`),`equation_latex`=VALUES(`equation_latex`),`word_latex`=VALUES(`word_latex`),`plain_description`=VALUES(`plain_description`),`equation_type`=VALUES(`equation_type`),`provenance`=VALUES(`provenance`),`source_id`=VALUES(`source_id`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
SET @eq_3_201:=LAST_INSERT_ID();
INSERT INTO `equations` (`equation_number`,`section_id`,`title`,`equation_latex`,`word_latex`,`plain_description`,`equation_type`,`provenance`,`source_id`,`derivation`,`assumptions`,`validation_status`,`created_revision_id`) VALUES
('3.202',@section_id,'Erstes transkritisches Gleichgewicht','x^\\ast=0','x^\\ast=0','Trivialer Gleichgewichtszweig der transkritischen Bifurkation.','derived','literature',@source_73_id,NULL,NULL,'checked',@revision_id)
ON DUPLICATE KEY UPDATE `equation_id`=LAST_INSERT_ID(`equation_id`),`section_id`=VALUES(`section_id`),`title`=VALUES(`title`),`equation_latex`=VALUES(`equation_latex`),`word_latex`=VALUES(`word_latex`),`plain_description`=VALUES(`plain_description`),`equation_type`=VALUES(`equation_type`),`provenance`=VALUES(`provenance`),`source_id`=VALUES(`source_id`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
SET @eq_3_202:=LAST_INSERT_ID();
INSERT INTO `equations` (`equation_number`,`section_id`,`title`,`equation_latex`,`word_latex`,`plain_description`,`equation_type`,`provenance`,`source_id`,`derivation`,`assumptions`,`validation_status`,`created_revision_id`) VALUES
('3.203',@section_id,'Zweites transkritisches Gleichgewicht','x^\\ast=\\mu','x^\\ast=\\mu','Nichttrivialer Gleichgewichtszweig der transkritischen Bifurkation.','derived','literature',@source_73_id,NULL,NULL,'checked',@revision_id)
ON DUPLICATE KEY UPDATE `equation_id`=LAST_INSERT_ID(`equation_id`),`section_id`=VALUES(`section_id`),`title`=VALUES(`title`),`equation_latex`=VALUES(`equation_latex`),`word_latex`=VALUES(`word_latex`),`plain_description`=VALUES(`plain_description`),`equation_type`=VALUES(`equation_type`),`provenance`=VALUES(`provenance`),`source_id`=VALUES(`source_id`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
SET @eq_3_203:=LAST_INSERT_ID();
INSERT INTO `equations` (`equation_number`,`section_id`,`title`,`equation_latex`,`word_latex`,`plain_description`,`equation_type`,`provenance`,`source_id`,`derivation`,`assumptions`,`validation_status`,`created_revision_id`) VALUES
('3.204',@section_id,'Normalform der Pitchfork-Bifurkation','\\dot{x}=\\mu x-x^3','\\dot{x}=\\mu x-x^3','Überkritische Pitchfork-Normalform.','model','literature',@source_73_id,NULL,NULL,'checked',@revision_id)
ON DUPLICATE KEY UPDATE `equation_id`=LAST_INSERT_ID(`equation_id`),`section_id`=VALUES(`section_id`),`title`=VALUES(`title`),`equation_latex`=VALUES(`equation_latex`),`word_latex`=VALUES(`word_latex`),`plain_description`=VALUES(`plain_description`),`equation_type`=VALUES(`equation_type`),`provenance`=VALUES(`provenance`),`source_id`=VALUES(`source_id`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
SET @eq_3_204:=LAST_INSERT_ID();
INSERT INTO `equations` (`equation_number`,`section_id`,`title`,`equation_latex`,`word_latex`,`plain_description`,`equation_type`,`provenance`,`source_id`,`derivation`,`assumptions`,`validation_status`,`created_revision_id`) VALUES
('3.205',@section_id,'Faktorisierte Gleichgewichtsbedingung der Pitchfork-Bifurkation','x\\left(\\mu-x^2\\right)=0','x\\left(\\mu-x^2\\right)=0','Faktorisierte stationäre Bedingung der Pitchfork-Normalform.','derived','literature',@source_73_id,NULL,NULL,'checked',@revision_id)
ON DUPLICATE KEY UPDATE `equation_id`=LAST_INSERT_ID(`equation_id`),`section_id`=VALUES(`section_id`),`title`=VALUES(`title`),`equation_latex`=VALUES(`equation_latex`),`word_latex`=VALUES(`word_latex`),`plain_description`=VALUES(`plain_description`),`equation_type`=VALUES(`equation_type`),`provenance`=VALUES(`provenance`),`source_id`=VALUES(`source_id`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
SET @eq_3_205:=LAST_INSERT_ID();
INSERT INTO `equations` (`equation_number`,`section_id`,`title`,`equation_latex`,`word_latex`,`plain_description`,`equation_type`,`provenance`,`source_id`,`derivation`,`assumptions`,`validation_status`,`created_revision_id`) VALUES
('3.206',@section_id,'Zentrales Pitchfork-Gleichgewicht','x^\\ast=0','x^\\ast=0','Zentraler Gleichgewichtszweig der Pitchfork-Bifurkation.','derived','literature',@source_73_id,NULL,NULL,'checked',@revision_id)
ON DUPLICATE KEY UPDATE `equation_id`=LAST_INSERT_ID(`equation_id`),`section_id`=VALUES(`section_id`),`title`=VALUES(`title`),`equation_latex`=VALUES(`equation_latex`),`word_latex`=VALUES(`word_latex`),`plain_description`=VALUES(`plain_description`),`equation_type`=VALUES(`equation_type`),`provenance`=VALUES(`provenance`),`source_id`=VALUES(`source_id`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
SET @eq_3_206:=LAST_INSERT_ID();
INSERT INTO `equations` (`equation_number`,`section_id`,`title`,`equation_latex`,`word_latex`,`plain_description`,`equation_type`,`provenance`,`source_id`,`derivation`,`assumptions`,`validation_status`,`created_revision_id`) VALUES
('3.207',@section_id,'Symmetriegebrochene Pitchfork-Gleichgewichte','x^\\ast=\\pm\\sqrt{\\mu}','x^\\ast=\\pm\\sqrt{\\mu}','Neue Gleichgewichtszweige nach der Symmetriebrechung.','derived','literature',@source_73_id,NULL,NULL,'checked',@revision_id)
ON DUPLICATE KEY UPDATE `equation_id`=LAST_INSERT_ID(`equation_id`),`section_id`=VALUES(`section_id`),`title`=VALUES(`title`),`equation_latex`=VALUES(`equation_latex`),`word_latex`=VALUES(`word_latex`),`plain_description`=VALUES(`plain_description`),`equation_type`=VALUES(`equation_type`),`provenance`=VALUES(`provenance`),`source_id`=VALUES(`source_id`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
SET @eq_3_207:=LAST_INSERT_ID();
INSERT INTO `equations` (`equation_number`,`section_id`,`title`,`equation_latex`,`word_latex`,`plain_description`,`equation_type`,`provenance`,`source_id`,`derivation`,`assumptions`,`validation_status`,`created_revision_id`) VALUES
('3.208',@section_id,'Normalform der Hopf-Bifurkation','\\dot{z}=(\\mu+i\\omega)z-|z|^2z','\\dot{z}=(\\mu+i\\omega)z-|z|^2z','Komplexe Normalform einer überkritischen Hopf-Bifurkation.','model','literature',@source_74_id,NULL,NULL,'checked',@revision_id)
ON DUPLICATE KEY UPDATE `equation_id`=LAST_INSERT_ID(`equation_id`),`section_id`=VALUES(`section_id`),`title`=VALUES(`title`),`equation_latex`=VALUES(`equation_latex`),`word_latex`=VALUES(`word_latex`),`plain_description`=VALUES(`plain_description`),`equation_type`=VALUES(`equation_type`),`provenance`=VALUES(`provenance`),`source_id`=VALUES(`source_id`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
SET @eq_3_208:=LAST_INSERT_ID();
INSERT INTO `equations` (`equation_number`,`section_id`,`title`,`equation_latex`,`word_latex`,`plain_description`,`equation_type`,`provenance`,`source_id`,`derivation`,`assumptions`,`validation_status`,`created_revision_id`) VALUES
('3.209',@section_id,'Kritischer Parameter','\\mu_c','\\mu_c','Bezeichnung des kritischen Parameterwertes.','definition','literature',@source_73_id,NULL,NULL,'checked',@revision_id)
ON DUPLICATE KEY UPDATE `equation_id`=LAST_INSERT_ID(`equation_id`),`section_id`=VALUES(`section_id`),`title`=VALUES(`title`),`equation_latex`=VALUES(`equation_latex`),`word_latex`=VALUES(`word_latex`),`plain_description`=VALUES(`plain_description`),`equation_type`=VALUES(`equation_type`),`provenance`=VALUES(`provenance`),`source_id`=VALUES(`source_id`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
SET @eq_3_209:=LAST_INSERT_ID();
INSERT INTO `equations` (`equation_number`,`section_id`,`title`,`equation_latex`,`word_latex`,`plain_description`,`equation_type`,`provenance`,`source_id`,`derivation`,`assumptions`,`validation_status`,`created_revision_id`) VALUES
('3.210',@section_id,'Spektrale Bifurkationsbedingung','\\operatorname{Re}\\left(\\lambda(\\mu_c)\\right)=0','\\operatorname{Re}\\left(\\lambda(\\mu_c)\\right)=0','Eigenwertbedingung am Bifurkationspunkt.','definition','literature',@source_73_id,NULL,NULL,'checked',@revision_id)
ON DUPLICATE KEY UPDATE `equation_id`=LAST_INSERT_ID(`equation_id`),`section_id`=VALUES(`section_id`),`title`=VALUES(`title`),`equation_latex`=VALUES(`equation_latex`),`word_latex`=VALUES(`word_latex`),`plain_description`=VALUES(`plain_description`),`equation_type`=VALUES(`equation_type`),`provenance`=VALUES(`provenance`),`source_id`=VALUES(`source_id`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
SET @eq_3_210:=LAST_INSERT_ID();
INSERT INTO `equations` (`equation_number`,`section_id`,`title`,`equation_latex`,`word_latex`,`plain_description`,`equation_type`,`provenance`,`source_id`,`derivation`,`assumptions`,`validation_status`,`created_revision_id`) VALUES
('3.211',@section_id,'Wechsel der Attraktormenge','A(\\mu^-)\\neq A(\\mu^+)','A(\\mu^-)\\neq A(\\mu^+)','Qualitative Änderung der asymptotischen Organisationsform.','model','literature',@source_72_id,NULL,NULL,'checked',@revision_id)
ON DUPLICATE KEY UPDATE `equation_id`=LAST_INSERT_ID(`equation_id`),`section_id`=VALUES(`section_id`),`title`=VALUES(`title`),`equation_latex`=VALUES(`equation_latex`),`word_latex`=VALUES(`word_latex`),`plain_description`=VALUES(`plain_description`),`equation_type`=VALUES(`equation_type`),`provenance`=VALUES(`provenance`),`source_id`=VALUES(`source_id`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
SET @eq_3_211:=LAST_INSERT_ID();

/* Gleichungssymbole, vollständig idempotent. */
INSERT INTO `equation_symbols` (`equation_id`,`symbol_latex`,`symbol_name`,`definition_text`,`unit_text`,`domain_text`,`symbol_order`) VALUES
(@eq_3_184,'\\mu','Kontrollparameter','Parameter der dynamischen Systemfamilie.',NULL,'\\mathbb{R}^p',1)
ON DUPLICATE KEY UPDATE `symbol_name`=VALUES(`symbol_name`),`definition_text`=VALUES(`definition_text`),`unit_text`=VALUES(`unit_text`),`domain_text`=VALUES(`domain_text`),`symbol_order`=VALUES(`symbol_order`);
INSERT INTO `equation_symbols` (`equation_id`,`symbol_latex`,`symbol_name`,`definition_text`,`unit_text`,`domain_text`,`symbol_order`) VALUES
(@eq_3_184,'F','Vektorfeld','Parameterabhängiges Entwicklungsgesetz.',NULL,'X\\times\\mathbb{R}^p\\to TX',2)
ON DUPLICATE KEY UPDATE `symbol_name`=VALUES(`symbol_name`),`definition_text`=VALUES(`definition_text`),`unit_text`=VALUES(`unit_text`),`domain_text`=VALUES(`domain_text`),`symbol_order`=VALUES(`symbol_order`);
INSERT INTO `equation_symbols` (`equation_id`,`symbol_latex`,`symbol_name`,`definition_text`,`unit_text`,`domain_text`,`symbol_order`) VALUES
(@eq_3_185,'A(\\mu)','Systemmatrix','Parameterabhängige lineare Systemmatrix.',NULL,'\\mathbb{R}^{n\\times n}',1)
ON DUPLICATE KEY UPDATE `symbol_name`=VALUES(`symbol_name`),`definition_text`=VALUES(`definition_text`),`unit_text`=VALUES(`unit_text`),`domain_text`=VALUES(`domain_text`),`symbol_order`=VALUES(`symbol_order`);
INSERT INTO `equation_symbols` (`equation_id`,`symbol_latex`,`symbol_name`,`definition_text`,`unit_text`,`domain_text`,`symbol_order`) VALUES
(@eq_3_186,'N','nichtlinearer Anteil','Nichtlinearer Anteil des Entwicklungsgesetzes.',NULL,NULL,1)
ON DUPLICATE KEY UPDATE `symbol_name`=VALUES(`symbol_name`),`definition_text`=VALUES(`definition_text`),`unit_text`=VALUES(`unit_text`),`domain_text`=VALUES(`domain_text`),`symbol_order`=VALUES(`symbol_order`);
INSERT INTO `equation_symbols` (`equation_id`,`symbol_latex`,`symbol_name`,`definition_text`,`unit_text`,`domain_text`,`symbol_order`) VALUES
(@eq_3_190,'\\xi','lokale Abweichung','Abweichung vom Gleichgewichtspunkt.',NULL,'\\mathbb{R}^n',1)
ON DUPLICATE KEY UPDATE `symbol_name`=VALUES(`symbol_name`),`definition_text`=VALUES(`definition_text`),`unit_text`=VALUES(`unit_text`),`domain_text`=VALUES(`domain_text`),`symbol_order`=VALUES(`symbol_order`);
INSERT INTO `equation_symbols` (`equation_id`,`symbol_latex`,`symbol_name`,`definition_text`,`unit_text`,`domain_text`,`symbol_order`) VALUES
(@eq_3_193,'J','Jacobi-Matrix','Ableitung des Vektorfeldes bezüglich des Zustandes.',NULL,'\\mathbb{R}^{n\\times n}',1)
ON DUPLICATE KEY UPDATE `symbol_name`=VALUES(`symbol_name`),`definition_text`=VALUES(`definition_text`),`unit_text`=VALUES(`unit_text`),`domain_text`=VALUES(`domain_text`),`symbol_order`=VALUES(`symbol_order`);
INSERT INTO `equation_symbols` (`equation_id`,`symbol_latex`,`symbol_name`,`definition_text`,`unit_text`,`domain_text`,`symbol_order`) VALUES
(@eq_3_194,'\\lambda_i','Eigenwert','i-ter Eigenwert der Jacobi-Matrix.',NULL,'\\mathbb{C}',1)
ON DUPLICATE KEY UPDATE `symbol_name`=VALUES(`symbol_name`),`definition_text`=VALUES(`definition_text`),`unit_text`=VALUES(`unit_text`),`domain_text`=VALUES(`domain_text`),`symbol_order`=VALUES(`symbol_order`);
INSERT INTO `equation_symbols` (`equation_id`,`symbol_latex`,`symbol_name`,`definition_text`,`unit_text`,`domain_text`,`symbol_order`) VALUES
(@eq_3_196,'\\mu_c','kritischer Parameter','Parameterwert mit verschwindendem Eigenwertrealteil.',NULL,'\\mathbb{R}',1)
ON DUPLICATE KEY UPDATE `symbol_name`=VALUES(`symbol_name`),`definition_text`=VALUES(`definition_text`),`unit_text`=VALUES(`unit_text`),`domain_text`=VALUES(`domain_text`),`symbol_order`=VALUES(`symbol_order`);
INSERT INTO `equation_symbols` (`equation_id`,`symbol_latex`,`symbol_name`,`definition_text`,`unit_text`,`domain_text`,`symbol_order`) VALUES
(@eq_3_197,'\\Phi_\\mu','parameterabhängiger Fluss','Fluss des Systems beim Parameterwert mu.',NULL,NULL,1)
ON DUPLICATE KEY UPDATE `symbol_name`=VALUES(`symbol_name`),`definition_text`=VALUES(`definition_text`),`unit_text`=VALUES(`unit_text`),`domain_text`=VALUES(`domain_text`),`symbol_order`=VALUES(`symbol_order`);
INSERT INTO `equation_symbols` (`equation_id`,`symbol_latex`,`symbol_name`,`definition_text`,`unit_text`,`domain_text`,`symbol_order`) VALUES
(@eq_3_208,'z','komplexe Zustandsvariable','Lokale komplexe Koordinate der Hopf-Normalform.',NULL,'\\mathbb{C}',1)
ON DUPLICATE KEY UPDATE `symbol_name`=VALUES(`symbol_name`),`definition_text`=VALUES(`definition_text`),`unit_text`=VALUES(`unit_text`),`domain_text`=VALUES(`domain_text`),`symbol_order`=VALUES(`symbol_order`);
INSERT INTO `equation_symbols` (`equation_id`,`symbol_latex`,`symbol_name`,`definition_text`,`unit_text`,`domain_text`,`symbol_order`) VALUES
(@eq_3_208,'\\omega','Eigenkreisfrequenz','Imaginärteil des kritischen Eigenwertpaares.',NULL,'\\mathbb{R}_{>0}',2)
ON DUPLICATE KEY UPDATE `symbol_name`=VALUES(`symbol_name`),`definition_text`=VALUES(`definition_text`),`unit_text`=VALUES(`unit_text`),`domain_text`=VALUES(`domain_text`),`symbol_order`=VALUES(`symbol_order`);
INSERT INTO `equation_symbols` (`equation_id`,`symbol_latex`,`symbol_name`,`definition_text`,`unit_text`,`domain_text`,`symbol_order`) VALUES
(@eq_3_211,'A(\\mu)','Attraktormenge','Parameterabhängige asymptotische Organisationsform.',NULL,NULL,1)
ON DUPLICATE KEY UPDATE `symbol_name`=VALUES(`symbol_name`),`definition_text`=VALUES(`definition_text`),`unit_text`=VALUES(`unit_text`),`domain_text`=VALUES(`domain_text`),`symbol_order`=VALUES(`symbol_order`);

/* Abschnittssymbole. */
INSERT INTO `symbols` (`symbol_latex`,`symbol_word_latex`,`symbol_name`,`definition_text`,`scope_type`,`first_section_id`,`first_equation_id`,`unit_text`,`domain_text`,`codomain_text`,`is_vector`,`is_matrix`,`is_operator`,`notes`,`validation_status`,`created_revision_id`) VALUES
('\\mu','\\mu','Kontrollparameter','Parameter, dessen Variation qualitative Änderungen der Dynamik auslösen kann.','section',@section_id,@eq_3_184,NULL,'\\mathbb{R}^p',NULL,0,0,0,'Zentrales Symbol des Abschnitts 3.2.8.','checked',@revision_id)
ON DUPLICATE KEY UPDATE `symbol_word_latex`=VALUES(`symbol_word_latex`),`symbol_name`=VALUES(`symbol_name`),`definition_text`=VALUES(`definition_text`),`first_section_id`=VALUES(`first_section_id`),`first_equation_id`=VALUES(`first_equation_id`),`domain_text`=VALUES(`domain_text`),`codomain_text`=VALUES(`codomain_text`),`is_vector`=VALUES(`is_vector`),`is_matrix`=VALUES(`is_matrix`),`is_operator`=VALUES(`is_operator`),`notes`=VALUES(`notes`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
INSERT INTO `symbols` (`symbol_latex`,`symbol_word_latex`,`symbol_name`,`definition_text`,`scope_type`,`first_section_id`,`first_equation_id`,`unit_text`,`domain_text`,`codomain_text`,`is_vector`,`is_matrix`,`is_operator`,`notes`,`validation_status`,`created_revision_id`) VALUES
('F','F','nichtlineares Vektorfeld','Parameterabhängiges Entwicklungsgesetz des Systems.','section',@section_id,@eq_3_184,NULL,'X\\times\\mathbb{R}^p','TX',0,0,1,'Zentrales Symbol des Abschnitts 3.2.8.','checked',@revision_id)
ON DUPLICATE KEY UPDATE `symbol_word_latex`=VALUES(`symbol_word_latex`),`symbol_name`=VALUES(`symbol_name`),`definition_text`=VALUES(`definition_text`),`first_section_id`=VALUES(`first_section_id`),`first_equation_id`=VALUES(`first_equation_id`),`domain_text`=VALUES(`domain_text`),`codomain_text`=VALUES(`codomain_text`),`is_vector`=VALUES(`is_vector`),`is_matrix`=VALUES(`is_matrix`),`is_operator`=VALUES(`is_operator`),`notes`=VALUES(`notes`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
INSERT INTO `symbols` (`symbol_latex`,`symbol_word_latex`,`symbol_name`,`definition_text`,`scope_type`,`first_section_id`,`first_equation_id`,`unit_text`,`domain_text`,`codomain_text`,`is_vector`,`is_matrix`,`is_operator`,`notes`,`validation_status`,`created_revision_id`) VALUES
('N(x,\\mu)','N(x,\\mu)','nichtlinearer Anteil','Nichtlinearer Anteil des Entwicklungsgesetzes.','section',@section_id,@eq_3_186,NULL,NULL,NULL,0,0,1,'Zentrales Symbol des Abschnitts 3.2.8.','checked',@revision_id)
ON DUPLICATE KEY UPDATE `symbol_word_latex`=VALUES(`symbol_word_latex`),`symbol_name`=VALUES(`symbol_name`),`definition_text`=VALUES(`definition_text`),`first_section_id`=VALUES(`first_section_id`),`first_equation_id`=VALUES(`first_equation_id`),`domain_text`=VALUES(`domain_text`),`codomain_text`=VALUES(`codomain_text`),`is_vector`=VALUES(`is_vector`),`is_matrix`=VALUES(`is_matrix`),`is_operator`=VALUES(`is_operator`),`notes`=VALUES(`notes`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
INSERT INTO `symbols` (`symbol_latex`,`symbol_word_latex`,`symbol_name`,`definition_text`,`scope_type`,`first_section_id`,`first_equation_id`,`unit_text`,`domain_text`,`codomain_text`,`is_vector`,`is_matrix`,`is_operator`,`notes`,`validation_status`,`created_revision_id`) VALUES
('\\xi','\\xi','lokale Abweichung','Lokale Abweichung vom Gleichgewichtspunkt.','section',@section_id,@eq_3_190,NULL,'\\mathbb{R}^n',NULL,1,0,0,'Zentrales Symbol des Abschnitts 3.2.8.','checked',@revision_id)
ON DUPLICATE KEY UPDATE `symbol_word_latex`=VALUES(`symbol_word_latex`),`symbol_name`=VALUES(`symbol_name`),`definition_text`=VALUES(`definition_text`),`first_section_id`=VALUES(`first_section_id`),`first_equation_id`=VALUES(`first_equation_id`),`domain_text`=VALUES(`domain_text`),`codomain_text`=VALUES(`codomain_text`),`is_vector`=VALUES(`is_vector`),`is_matrix`=VALUES(`is_matrix`),`is_operator`=VALUES(`is_operator`),`notes`=VALUES(`notes`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
INSERT INTO `symbols` (`symbol_latex`,`symbol_word_latex`,`symbol_name`,`definition_text`,`scope_type`,`first_section_id`,`first_equation_id`,`unit_text`,`domain_text`,`codomain_text`,`is_vector`,`is_matrix`,`is_operator`,`notes`,`validation_status`,`created_revision_id`) VALUES
('J','J','Jacobi-Matrix','Linearisierung des Vektorfeldes am Gleichgewichtspunkt.','section',@section_id,@eq_3_193,NULL,'\\mathbb{R}^{n\\times n}','\\mathbb{R}^{n\\times n}',0,1,0,'Zentrales Symbol des Abschnitts 3.2.8.','checked',@revision_id)
ON DUPLICATE KEY UPDATE `symbol_word_latex`=VALUES(`symbol_word_latex`),`symbol_name`=VALUES(`symbol_name`),`definition_text`=VALUES(`definition_text`),`first_section_id`=VALUES(`first_section_id`),`first_equation_id`=VALUES(`first_equation_id`),`domain_text`=VALUES(`domain_text`),`codomain_text`=VALUES(`codomain_text`),`is_vector`=VALUES(`is_vector`),`is_matrix`=VALUES(`is_matrix`),`is_operator`=VALUES(`is_operator`),`notes`=VALUES(`notes`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
INSERT INTO `symbols` (`symbol_latex`,`symbol_word_latex`,`symbol_name`,`definition_text`,`scope_type`,`first_section_id`,`first_equation_id`,`unit_text`,`domain_text`,`codomain_text`,`is_vector`,`is_matrix`,`is_operator`,`notes`,`validation_status`,`created_revision_id`) VALUES
('\\lambda_i','\\lambda_i','Eigenwert','Eigenwert der Jacobi-Matrix.','section',@section_id,@eq_3_194,NULL,'\\mathbb{C}',NULL,0,0,0,'Zentrales Symbol des Abschnitts 3.2.8.','checked',@revision_id)
ON DUPLICATE KEY UPDATE `symbol_word_latex`=VALUES(`symbol_word_latex`),`symbol_name`=VALUES(`symbol_name`),`definition_text`=VALUES(`definition_text`),`first_section_id`=VALUES(`first_section_id`),`first_equation_id`=VALUES(`first_equation_id`),`domain_text`=VALUES(`domain_text`),`codomain_text`=VALUES(`codomain_text`),`is_vector`=VALUES(`is_vector`),`is_matrix`=VALUES(`is_matrix`),`is_operator`=VALUES(`is_operator`),`notes`=VALUES(`notes`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
INSERT INTO `symbols` (`symbol_latex`,`symbol_word_latex`,`symbol_name`,`definition_text`,`scope_type`,`first_section_id`,`first_equation_id`,`unit_text`,`domain_text`,`codomain_text`,`is_vector`,`is_matrix`,`is_operator`,`notes`,`validation_status`,`created_revision_id`) VALUES
('\\mu_c','\\mu_c','kritischer Parameterwert','Parameterwert einer möglichen Bifurkation.','section',@section_id,@eq_3_196,NULL,'\\mathbb{R}',NULL,0,0,0,'Zentrales Symbol des Abschnitts 3.2.8.','checked',@revision_id)
ON DUPLICATE KEY UPDATE `symbol_word_latex`=VALUES(`symbol_word_latex`),`symbol_name`=VALUES(`symbol_name`),`definition_text`=VALUES(`definition_text`),`first_section_id`=VALUES(`first_section_id`),`first_equation_id`=VALUES(`first_equation_id`),`domain_text`=VALUES(`domain_text`),`codomain_text`=VALUES(`codomain_text`),`is_vector`=VALUES(`is_vector`),`is_matrix`=VALUES(`is_matrix`),`is_operator`=VALUES(`is_operator`),`notes`=VALUES(`notes`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
INSERT INTO `symbols` (`symbol_latex`,`symbol_word_latex`,`symbol_name`,`definition_text`,`scope_type`,`first_section_id`,`first_equation_id`,`unit_text`,`domain_text`,`codomain_text`,`is_vector`,`is_matrix`,`is_operator`,`notes`,`validation_status`,`created_revision_id`) VALUES
('\\Phi_\\mu','\\Phi_\\mu','parameterabhängiger Fluss','Dynamischer Fluss für einen festen Parameterwert.','section',@section_id,@eq_3_197,NULL,NULL,NULL,0,0,1,'Zentrales Symbol des Abschnitts 3.2.8.','checked',@revision_id)
ON DUPLICATE KEY UPDATE `symbol_word_latex`=VALUES(`symbol_word_latex`),`symbol_name`=VALUES(`symbol_name`),`definition_text`=VALUES(`definition_text`),`first_section_id`=VALUES(`first_section_id`),`first_equation_id`=VALUES(`first_equation_id`),`domain_text`=VALUES(`domain_text`),`codomain_text`=VALUES(`codomain_text`),`is_vector`=VALUES(`is_vector`),`is_matrix`=VALUES(`is_matrix`),`is_operator`=VALUES(`is_operator`),`notes`=VALUES(`notes`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);
INSERT INTO `symbols` (`symbol_latex`,`symbol_word_latex`,`symbol_name`,`definition_text`,`scope_type`,`first_section_id`,`first_equation_id`,`unit_text`,`domain_text`,`codomain_text`,`is_vector`,`is_matrix`,`is_operator`,`notes`,`validation_status`,`created_revision_id`) VALUES
('A(\\mu)','A(\\mu)','parameterabhängiger Attraktor','Asymptotische Organisationsform des Systems beim Parameterwert mu.','section',@section_id,@eq_3_211,NULL,NULL,NULL,0,0,0,'Zentrales Symbol des Abschnitts 3.2.8.','checked',@revision_id)
ON DUPLICATE KEY UPDATE `symbol_word_latex`=VALUES(`symbol_word_latex`),`symbol_name`=VALUES(`symbol_name`),`definition_text`=VALUES(`definition_text`),`first_section_id`=VALUES(`first_section_id`),`first_equation_id`=VALUES(`first_equation_id`),`domain_text`=VALUES(`domain_text`),`codomain_text`=VALUES(`codomain_text`),`is_vector`=VALUES(`is_vector`),`is_matrix`=VALUES(`is_matrix`),`is_operator`=VALUES(`is_operator`),`notes`=VALUES(`notes`),`validation_status`='checked',`created_revision_id`=VALUES(`created_revision_id`);

INSERT INTO `section_change_log` (`revision_id`,`section_id`,`change_type`,`object_type`,`object_reference`,`change_summary`,`previous_value`,`new_value`) VALUES
(@revision_id,@section_id,'rewritten','section','3.2.8','Abschnitt vollständig neu gefasst.',NULL,'Nichtlinearität, Linearisierung, Bifurkationen und emergente Strukturwechsel.'),
(@revision_id,@section_id,'source_added','sources','[73]–[74]','Zwei neue Quellen registriert.',NULL,'Kuznetsov [73], Guckenheimer/Holmes [74].'),
(@revision_id,@section_id,'definition_added','definitions','Def. 3.2.8.1–Def. 3.2.8.11','Elf Definitionen registriert.',NULL,'Nichtlinearität bis emergenter Strukturwechsel.'),
(@revision_id,@section_id,'equation_added','equations','(3.184)–(3.211)','28 Gleichungen registriert.',NULL,'Nichtlinearität, Linearisierung, Bifurkationsnormalformen und Attraktorwechsel.');

INSERT INTO `repository_counters` (`counter_key`,`counter_value`) VALUES
('next_citation_number','75'),('next_equation_number','3.212'),('last_edited_section','3.2.8'),('last_repository_revision','RKB-2026-07-15-K3.2.8-NEUFASSUNG-V2')
ON DUPLICATE KEY UPDATE `counter_value`=VALUES(`counter_value`);
COMMIT;

/* Kontrollabfragen. */
SELECT `revision_id`,`revision_code`,`parent_revision_id`,`scope_reference`,`version_label` FROM `repository_revisions` WHERE `revision_code`='RKB-2026-07-15-K3.2.8-NEUFASSUNG-V2';
SELECT `section_code`,`title`,`status`,`is_original_contribution`,`notes` FROM `dissertation_sections` WHERE `section_code`='3.2.8';
SELECT `citation_number`,`source_key`,`title`,`verification_status` FROM `sources` WHERE `citation_number` BETWEEN 73 AND 74 ORDER BY `citation_number`;
SELECT COUNT(*) AS `definition_count` FROM `definitions` WHERE `section_id`=@section_id;
SELECT COUNT(*) AS `equation_count` FROM `equations` WHERE `section_id`=@section_id;
SELECT COUNT(*) AS `equation_symbol_count` FROM `equation_symbols` es JOIN `equations` e ON e.`equation_id`=es.`equation_id` WHERE e.`section_id`=@section_id;
SELECT `counter_key`,`counter_value` FROM `repository_counters` WHERE `counter_key` IN ('next_citation_number','next_equation_number','last_edited_section','last_repository_revision') ORDER BY `counter_key`;
SELECT COUNT(*) AS `duplicate_equation_numbers` FROM (SELECT `equation_number` FROM `equations` GROUP BY `equation_number` HAVING COUNT(*)>1) d;
SELECT COUNT(*) AS `duplicate_equation_symbols` FROM (SELECT `equation_id`,`symbol_latex` FROM `equation_symbols` GROUP BY `equation_id`,`symbol_latex` HAVING COUNT(*)>1) d;
SELECT COUNT(*) AS `missing_word_latex` FROM `equations` WHERE `section_id`=@section_id AND (`word_latex` IS NULL OR TRIM(`word_latex`)='');