
import pandas as pd

# Schülerdaten
schueler_columns = [
    "Name", "Klasse", "Probeschüler", "Erhält keine Noten", "Versetzungsgefährdet",
    "Teilnahmenachweis erforderlich", "Protokoll", "Extras", "Vertraulich"
]

schueler_data = {
    "Name": "König, Karl",
    "Klasse": "6 GYM",
    "Probeschüler": 1,
    "Erhält keine Noten": 1,
    "Versetzungsgefährdet": 1,
    "Teilnahmenachweis erforderlich": 1,
    "Protokoll": 1,
    "Extras": 1,
    "Vertraulich": 1
}

schueler_df = pd.DataFrame([schueler_data], columns=schueler_columns)

# Bewertungsdaten
bewertungs_columns = [
    "Fach", "Datum", "Lehrkraft", "Thema", "Absprachen", "Mitarbeit", "Fleißig", "Selbstständig",
    "Vorbereitet", "Konzentriert", "Lernfortschritt", "Beherrscht Thema", "Transferdenken", "Basiswissen", "Freitext"
]

bewertungen_data = [
    {
        "Fach": "MAT",
        "Datum": "2025-05-28",
        "Lehrkraft": "Thiele, Dipl.-Ing. Olaf",
        "Thema": "Geometrie: Prism",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 0,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 0,
        "Transferdenken": 0,
        "Basiswissen": 1,
        "Freitext": "Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, Materialien fehlen, Lernfortschritt erzielt, Basiswissen vorhanden"
    },
    {
        "Fach": "MAT",
        "Datum": "2025-05-23",
        "Lehrkraft": "Städter, Kathleen",
        "Thema": "Geometrie Prismen",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 0,
        "Transferdenken": 0,
        "Basiswissen": 0,
        "Freitext": "Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, vorbereitet, Lernfortschritt erzielt"
    },
    {
        "Fach": "MAT",
        "Datum": "2025-05-22",
        "Lehrkraft": "Thiele, Dipl.-Ing. Olaf",
        "Thema": "Geometrie: Prism",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 1,
        "Transferdenken": 0,
        "Basiswissen": 0,
        "Freitext": "Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, vorbereitet, Lernfortschritt erzielt, beherrscht Thema"
    },
    {
        "Fach": "MAT",
        "Datum": "2025-05-21",
        "Lehrkraft": "Thiele, Dipl.-Ing. Olaf",
        "Thema": "Grundrechenarten: schrftlGRAalle",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 1,
        "Transferdenken": 0,
        "Basiswissen": 0,
        "Freitext": "Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, vorbereitet, Lernfortschritt erzielt, beherrscht Thema"
    },
    {
        "Fach": "MAT",
        "Datum": "2025-05-16",
        "Lehrkraft": "Thiele, Dipl.-Ing. Olaf",
        "Thema": "Grundrechenarten: schrftlGRA",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 1,
        "Transferdenken": 0,
        "Basiswissen": 0,
        "Freitext": "Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, vorbereitet, Lernfortschritt erzielt, beherrscht Thema"
    },
    {
        "Fach": "MAT",
        "Datum": "2025-05-14",
        "Lehrkraft": "Thiele, Dipl.-Ing. Olaf",
        "Thema": "Geometrie: Prismen",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 0,
        "Transferdenken": 0,
        "Basiswissen": 1,
        "Freitext": "Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, vorbereitet, Lernfortschritt erzielt, Basiswissen vorhanden"
    },
    {
        "Fach": "MAT",
        "Datum": "2025-05-13",
        "Lehrkraft": "Thiele, Dipl.-Ing. Olaf",
        "Thema": "Grundrechenarten: alle",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 1,
        "Transferdenken": 0,
        "Basiswissen": 0,
        "Freitext": "Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, vorbereitet, Lernfortschritt erzielt, beherrscht Thema"
    },
    {
        "Fach": "MAT",
        "Datum": "2025-05-09",
        "Lehrkraft": "Thiele, Dipl.-Ing. Olaf",
        "Thema": "Geometrie: Vierecke",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 1,
        "Transferdenken": 0,
        "Basiswissen": 0,
        "Freitext": "Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, vorbereitet, Lernfortschritt erzielt, beherrscht Thema"
    },
    {
        "Fach": "MAT",
        "Datum": "2025-05-07",
        "Lehrkraft": "Thiele, Dipl.-Ing. Olaf",
        "Thema": "Geometrie: VE",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 0,
        "Transferdenken": 0,
        "Basiswissen": 1,
        "Freitext": "Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, vorbereitet, Lernfortschritt erzielt, Basiswissen vorhanden"
    },
    {
        "Fach": "MAT",
        "Datum": "2025-05-02",
        "Lehrkraft": "Thiele, Dipl.-Ing. Olaf",
        "Thema": "Grundrechenarten: schrftlDiv selbst",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 1,
        "Transferdenken": 0,
        "Basiswissen": 0,
        "Freitext": "Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, vorbereitet, Lernfortschritt erzielt, beherrscht Thema"
    },
    {
        "Fach": "MAT",
        "Datum": "2025-04-30",
        "Lehrkraft": "Thiele, Dipl.-Ing. Olaf",
        "Thema": "Grundrechenarten: Urschleim schrftlDiv",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 0,
        "Transferdenken": 0,
        "Basiswissen": 1,
        "Freitext": "Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, vorbereitet, Lernfortschritt erzielt, Basiswissen vorhanden"
    },
    {
        "Fach": "MAT",
        "Datum": "2025-04-17",
        "Lehrkraft": "Thiele, Dipl.-Ing. Olaf",
        "Thema": "Grundrechenarten: MulDezZ",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 1,
        "Transferdenken": 0,
        "Basiswissen": 0,
        "Freitext": "Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, vorbereitet, Lernfortschritt erzielt, beherrscht Thema"
    },
    {
        "Fach": "MAT",
        "Datum": "2025-04-16",
        "Lehrkraft": "Thiele, Dipl.-Ing. Olaf",
        "Thema": "Brüche: Kürzen",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 1,
        "Transferdenken": 0,
        "Basiswissen": 0,
        "Freitext": "Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, vorbereitet, Lernfortschritt erzielt, beherrscht Thema"
    },
    {
        "Fach": "MAT",
        "Datum": "2025-04-11",
        "Lehrkraft": "Thiele, Dipl.-Ing. Olaf",
        "Thema": "Grundrechenarten: schrft Div",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 0,
        "Transferdenken": 0,
        "Basiswissen": 1,
        "Freitext": "Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, vorbereitet, Lernfortschritt erzielt, Basiswissen vorhanden"
    },
    {
        "Fach": "MAT",
        "Datum": "2025-04-09",
        "Lehrkraft": "Thiele, Dipl.-Ing. Olaf",
        "Thema": "Brüche: Kürzen",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 1,
        "Transferdenken": 0,
        "Basiswissen": 0,
        "Freitext": "Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, vorbereitet, Lernfortschritt erzielt, beherrscht Thema"
    },
    {
        "Fach": "MAT",
        "Datum": "2025-04-04",
        "Lehrkraft": "Thiele, Dipl.-Ing. Olaf",
        "Thema": "Dreiecke Vorb. LK",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 0,
        "Transferdenken": 0,
        "Basiswissen": 1,
        "Freitext": "Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, vorbereitet, Lernfortschritt erzielt, Basiswissen vorhanden"
    },
    {
        "Fach": "MAT",
        "Datum": "2025-04-02",
        "Lehrkraft": "Thiele, Dipl.-Ing. Olaf",
        "Thema": "Brüche: Kürzen",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 1,
        "Transferdenken": 0,
        "Basiswissen": 0,
        "Freitext": "Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, vorbereitet, Lernfortschritt erzielt, beherrscht Thema"
    },
    {
        "Fach": "MAT",
        "Datum": "2025-03-28",
        "Lehrkraft": "Thiele, Dipl.-Ing. Olaf",
        "Thema": "Geometrie: Dreiecke",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 0,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 0,
        "Transferdenken": 0,
        "Basiswissen": 1,
        "Freitext": "Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, Materialien fehlen, Lernfortschritt erzielt, Basiswissen vorhanden"
    },
    {
        "Fach": "MAT",
        "Datum": "2025-03-27",
        "Lehrkraft": "Trigkidis, Dimitrios",
        "Thema": "Geometrie: Winkel messen und zeichnen",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 0,
        "Transferdenken": 0,
        "Basiswissen": 0,
        "Freitext": "Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, vorbereitet, konzentriert, Lernfortschritt erzielt"
    },
    {
        "Fach": "MAT",
        "Datum": "2025-03-21",
        "Lehrkraft": "Thiele, Dipl.-Ing. Olaf",
        "Thema": "Korrektur LK",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 0,
        "Transferdenken": 0,
        "Basiswissen": 1,
        "Freitext": "Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, vorbereitet, Lernfortschritt erzielt, Basiswissen vorhanden"
    },
    {
        "Fach": "MAT",
        "Datum": "2025-03-19",
        "Lehrkraft": "Thiele, Dipl.-Ing. Olaf",
        "Thema": "Geometrie: Winkelbestimmung",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 0,
        "Transferdenken": 0,
        "Basiswissen": 1,
        "Freitext": "Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, vorbereitet, Lernfortschritt erzielt, Basiswissen vorhanden"
    },
        {
        "Fach": "MAT",
        "Datum": "2025-03-14",
        "Lehrkraft": "Thiele, Dipl.-Ing. Olaf",
        "Thema": "Geometrie: DreiQuRecht",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 1,
        "Transferdenken": 0,
        "Basiswissen": 0,
        "Freitext": "Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, vorbereitet, Lernfortschritt erzielt, beherrscht Thema"
    },
    {
        "Fach": "MAT",
        "Datum": "2025-03-12",
        "Lehrkraft": "Thiele, Dipl.-Ing. Olaf",
        "Thema": "Dreieck: Konstruktion",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 1,
        "Lernfortschritt": 0,
        "Beherrscht Thema": 1,
        "Transferdenken": 0,
        "Basiswissen": 0,
        "Freitext": "Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, vorbereitet, beherrscht Thema"
    },
    {
        "Fach": "MAT",
        "Datum": "2025-03-11",
        "Lehrkraft": "Thiele, Dipl.-Ing. Olaf",
        "Thema": "Grundrechenarten: Add./Sub schriftl",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 1,
        "Lernfortschritt": 0,
        "Beherrscht Thema": 0,
        "Transferdenken": 0,
        "Basiswissen": 0,
        "Freitext": "Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, vorbereitet"
    },
    {
        "Fach": "MAT",
        "Datum": "2025-03-11",
        "Lehrkraft": "Thiele, Dipl.-Ing. Olaf",
        "Thema": "Grundrechenarten: Ganzwertaufgabe",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 0,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 0,
        "Transferdenken": 0,
        "Basiswissen": 1,
        "Freitext": "Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, vorbereitet"
    },
    {
        "Fach": "MAT",
        "Datum": "2025-03-07",
        "Lehrkraft": "Thiele, Dipl.-Ing. Olaf",
        "Thema": "GanzWAufg",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 1,
        "Transferdenken": 1,
        "Basiswissen": 0,
        "Freitext": "Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, vorbereitet, Lernfortschritt erzielt, beherrscht Thema"
    },
    {
        "Fach": "MAT",
        "Datum": "2025-03-05",
        "Lehrkraft": "Thiele, Dipl.-Ing. Olaf",
        "Thema": "Vorb LK / Prop / Fkt",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 1,
        "Transferdenken": 0,
        "Basiswissen": 0,
        "Freitext": "Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, vorbereitet, Lernfortschritt erzielt, beherrscht Thema"
    },
        {
        "Fach": "MAT",
        "Datum": "2025-02-12",
        "Lehrkraft": "Thiele, Dipl.-Ing. Olaf",
        "Thema": "Vorb.LK",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 0,
        "Transferdenken": 1,
        "Basiswissen": 1,
        "Freitext": "Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, vorbereitet, Lernfortschritt erzielt, Basiswissen vorhanden"
    },
    {
        "Fach": "MAT",
        "Datum": "2025-02-11",
        "Lehrkraft": "Thiele, Dipl.-Ing. Olaf",
        "Thema": "Dreisatz",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 1,
        "Transferdenken": 1,
        "Basiswissen": 0,
        "Freitext": "Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, vorbereitet, Lernfortschritt erzielt, beherrscht Thema"
    },
    {
        "Fach": "MAT",
        "Datum": "2025-01-27",
        "Lehrkraft": "Thiele, Dipl.-Ing. Olaf",
        "Thema": "Proportionalität",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 1,
        "Transferdenken": 1,
        "Basiswissen": 0,
        "Freitext": "Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, vorbereitet, Lernfortschritt erzielt, beherrscht Thema"
    },
        {
        "Fach": "MAT",
        "Datum": "2025-01-15",
        "Lehrkraft": "Djalilpoor, Sam",
        "Thema": "Zuordnungen",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 1,
        "Transferdenken": 0,
        "Basiswissen": 1,
        "Freitext": "Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, vorbereitet, konzentriert, Lernfortschritt erzielt, Basiswissen vorhanden"
    },
    {
        "Fach": "MAT",
        "Datum": "2025-01-14",
        "Lehrkraft": "Scheibe, Sophia",
        "Thema": "Proportionalität",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 0,
        "Transferdenken": 1,
        "Basiswissen": 1,
        "Freitext": "Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, vorbereitet"
    },
    {
        "Fach": "MAT",
        "Datum": "2025-01-10",
        "Lehrkraft": "Nößler, Brian",
        "Thema": "Porportionalität",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 0,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 0,
        "Transferdenken": 0,
        "Basiswissen": 1,
        "Freitext": "Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, Lernfortschritt erzielt, Basiswissen vorhanden"
    },
            {
        "Fach": "MAT",
        "Datum": "2025-01-08",
        "Lehrkraft": "Djalilpoor, Sam",
        "Thema": "Koordinatensystem",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 1,
        "Transferdenken": 0,
        "Basiswissen": 1,
        "Freitext": "Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, vorbereitet, konzentriert, Lernfortschritt erzielt, Basiswissen vorhanden"
    },
    {
        "Fach": "MAT",
        "Datum": "2025-01-06",
        "Lehrkraft": "Nößler, Brian",
        "Thema": "Proportionale Zuordnung",
        " 
