import pandas as pd

# Schülerdaten
schueler_columns = [
    "Name", "Klasse", "Probeschüler", "Erhält keine Noten", "Versetzungsgefährdet",
    "Teilnahmenachweis erforderlich", "Protokoll", "Extras", "Vertraulich"
]

schueler_data = {
    "Name": "Leidereiter, Mia",
    "Klasse": "3 GR",
    "Probeschüler": 1,
    "Erhält keine Noten": 1,
    "Versetzungsgefährdet": 1,
    "Teilnahmenachweis erforderlich": 1,
    "Protokoll": 1,
    "Extras": 1,
    "Vertraulich": 1
}

schueler_df = pd.DataFrame([schueler_data], columns=schueler_columns)

# Bewertungsdaten
bewertungs_columns = [
    "Fach", "Datum", "Lehrkraft", "Thema", "Absprachen", "Mitarbeit", "Fleißig", "Selbstständig",
    "Vorbereitet", "Konzentriert", "Lernfortschritt", "Beherrscht Thema", "Transferdenken", "Basiswissen", "Freitext"
]

bewertungen_data = [
    {
        "Fach": "MAT",
        "Datum": "2025-05-27",
        "Lehrkraft": "Kirsche, Emely",
        "Thema": "Grundrechenarten: Halbschriftliches Dividieren",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 0,
        "Selbstständig": 0,
        "Vorbereitet": 0,
        "Konzentriert": 0,
        "Lernfortschritt": 0,
        "Beherrscht Thema": 0,
        "Transferdenken": 0,
        "Basiswissen": 1,
        "Freitext": "Absprachen einhaltend, beteiligt sich / gute Mitarbeit, benötigt Aufforderung, Basiswissen vorhanden"
    },
    {
        "Fach": "MAT",
        "Datum": "2025-05-23",
        "Lehrkraft": "Städter, Kathleen",
        "Thema": "weitere Themen: Steigerung von Adjektiven",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 0,
        "Konzentriert": 0,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 0,
        "Transferdenken": 0,
        "Basiswissen": 0,
        "Freitext": "beteiligt sich / gute Mitarbeit, Absprachen einhaltend, fleißig / bemüht, arbeitet selbstständig, Lernfortschritt erzielt"
    },
    {
        "Fach": "MAT",
        "Datum": "2025-05-20",
        "Lehrkraft": "Kirsche, Emely",
        "Thema": "Grundrechenarten: Schriftliches Addieren und Subtrahieren",
        "Absprachen": 0,
        "Mitarbeit": 1,
        "Fleißig": 0,
        "Selbstständig": 0,
        "Vorbereitet": 0,
        "Konzentriert": 0,
        "Lernfortschritt": 0,
        "Beherrscht Thema": 0,
        "Transferdenken": 0,
        "Basiswissen": 1,
        "Freitext": "beteiligt sich / gute Mitarbeit, unkonzentriert, benötigt Aufforderung, Basiswissen vorhanden"
    },
    {
        "Fach": "MAT",
        "Datum": "2025-05-16",
        "Lehrkraft": "Hartmann, Tiia",
        "Thema": "Rechengesetze und Regeln: Umgang mit der Uhr",
        "Absprachen": 0,
        "Mitarbeit": 0,
        "Fleißig": 1,
        "Selbstständig": 0,
        "Vorbereitet": 0,
        "Konzentriert": 0,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 0,
        "Transferdenken": 0,
        "Basiswissen": 1,
        "Freitext": "sehr interessiert jedoch leicht ablenkbar, mehr eigeninitiative erforderlich, fleißig / bemüht, benötigt Aufforderung, unkonzentriert, Basiswissen vorhanden, Lernfortschritt erzielt"
    },
    {
        "Fach": "DEU",
        "Datum": "2025-04-30",
        "Lehrkraft": "Tahir, Honya",
        "Thema": "Lesen: Textverständnis, Leseübungen",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 0,
        "Konzentriert": 1,
        "Lernfortschritt": 0,
        "Beherrscht Thema": 0,
        "Transferdenken": 0,
        "Basiswissen": 1,
        "Freitext": "Mia hat das Lesen und Textverständnis geübt. Sie hat die Aufgaben teils selbstständig gelöst. Sie hat gut und konzentriert mitgearbeitet. Sie musste nicht aufgefordert werden, die Aufgaben zu lösen., Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, Basiswissen vorhanden"
    },
    {
        "Fach": "DEU",
        "Datum": "2025-02-12",
        "Lehrkraft": "Scheibe, Sophia",
        "Thema": "Sie bemüht sich deutlich, muss aber eigenständiger werden und Initiative zeigen.",
        "Absprachen": 0,
        "Mitarbeit": 0,
        "Fleißig": 0,
        "Selbstständig": 0,
        "Vorbereitet": 0,
        "Konzentriert": 0,
        "Lernfortschritt": 0,
        "Beherrscht Thema": 0,
        "Transferdenken": 0,
        "Basiswissen": 0,
        "Freitext": "Sie bemüht sich deutlich, muss aber eigenständiger werden und Initiative zeigen."
    },
    {
        "Fach": "MAT",
        "Datum": "2025-04-10",
        "Lehrkraft": "Heitmann, Nele",
        "Thema": "Grundrechenarten: Multiplikation und Einmaleins",
        "Absprachen": 0,
        "Mitarbeit": 0,
        "Fleißig": 0,
        "Selbstständig": 0,
        "Vorbereitet": 0,
        "Konzentriert": 0,
        "Lernfortschritt": 0,
        "Beherrscht Thema": 0,
        "Transferdenken": 0,
        "Basiswissen": 1,
        "Freitext": "Mia hatte leider keine Materialien mit und das Thema Schriftliche Multiplikation komplett abgelehnt. Eine Aufgabe zum kleinen Einmaleins wurde nur nach mehrmaligem Auffordern bearbeitet und Mia und Kiara lenken sich extremst gegenseitig ab., desinteressiert / gleichgültig, störend / blockierend / resignierend, Absprachen nicht einhaltend, benötigt Aufforderung, unkonzentriert, Materialien fehlen, Basiswissen vorhanden, Unverständnis"
    },
    {
        "Fach": "MAT",
        "Datum": "2025-04-04",
        "Lehrkraft": "Trigkidis, Dimitrios",
        "Thema": "Grundrechenarten: Multiplikation",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 0,
        "Selbstständig": 1,
        "Vorbereitet": 0,
        "Konzentriert": 0,
        "Lernfortschritt": 0,
        "Beherrscht Thema": 0,
        "Transferdenken": 0,
        "Basiswissen": 1,
        "Freitext": "Mia hat einen Test über Leiter- Nichtleiter berichtigt und dann Multiplikationen geübt., Absprachen einhaltend, beteiligt sich / gute Mitarbeit, unkonzentriert, arbeitet selbstständig, Basiswissen vorhanden"
    },
    {
        "Fach": "DEU",
        "Datum": "2025-04-02",
        "Lehrkraft": "Tahir, Honya",
        "Thema": "Schreiben: Doppellaute (ai, ei, äu, eu)",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 0,
        "Transferdenken": 0,
        "Basiswissen": 1,
        "Freitext": "Mia hat die Aufgaben gut gelöst. Manchmal hat sie Hilfe benötigt, jedoch ist Basiswissen vorhanden., Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, vorbereitet, Lernfortschritt erzielt, Basiswissen vorhanden"
    },
    {
        "Fach": "DEU",
        "Datum": "2025-03-26",
        "Lehrkraft": "Tahir, Honya",
        "Thema": "Lesen: Leseverständnis",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 0,
        "Transferdenken": 0,
        "Basiswissen": 1,
        "Freitext": "Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, vorbereitet, Basiswissen vorhanden, Lernfortschritt erzielt"
    },
    {
        "Fach": "DEU",
        "Datum": "2025-03-05",
        "Lehrkraft": "Riedel, Christin",
        "Thema": "Lesen: Leseverständnis",
        "Absprachen": 0,
        "Mitarbeit": 1,
        "Fleißig": 0,
        "Selbstständig": 0,
        "Vorbereitet": 0,
        "Konzentriert": 0,
        "Lernfortschritt": 0,
        "Beherrscht Thema": 0,
        "Transferdenken": 0,
        "Basiswissen": 1,
        "Freitext": "beteiligt sich / gute Mitarbeit, störend / blockierend / resignierend, benötigt Aufforderung, unkonzentriert, Materialien fehlen, Unverständnis, Basiswissen vorhanden"
    },
    {
        "Fach": "MAT",
        "Datum": "2025-02-28",
        "Lehrkraft": "Reindel, Abby",
        "Thema": "Grundrechenarten: schriftliche Addition",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 1,
        "Transferdenken": 0,
        "Basiswissen": 0,
        "Freitext": "Wir haben das neue Thema schriftliche Addition geübt. Sie beherrscht das Thema gut und arbeitete konzentriert., Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, vorbereitet, beherrscht Thema, Lernfortschritt erzielt"
    },
    {
        "Fach": "MAT",
        "Datum": "2025-02-14",
        "Lehrkraft": "Wolter, Kathrin",
        "Thema": "Grundrechenarten: Einmaleins",
        "Absprachen": 1,
        "Mitarbeit": 0,
        "Fleißig": 0,
        "Selbstständig": 1,
        "Vorbereitet": 0,
        "Konzentriert": 0,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 0,
        "Transferdenken": 0,
        "Basiswissen": 1,
        "Freitext": "Absprachen einhaltend, arbeitet selbstständig, Lernfortschritt erzielt, Basiswissen vorhanden"
    },
    {
        "Fach": "DEU",
        "Datum": "2025-02-19",
        "Lehrkraft": "Riedel, Christin",
        "Thema": "Lesen: Märchen",
        "Absprachen": 0,
        "Mitarbeit": 0,
        "Fleißig": 0,
        "Selbstständig": 0,
        "Vorbereitet": 0,
        "Konzentriert": 0,
        "Lernfortschritt": 0,
        "Beherrscht Thema": 0,
        "Transferdenken": 1,
        "Basiswissen": 1,
        "Freitext": "Leseübung, störend / blockierend / resignierend, desinteressiert / gleichgültig, Absprachen nicht einhaltend, benötigt Aufforderung, unkonzentriert, Materialien fehlen, fähig zu Transferdenken, Basiswissen vorhanden"
    },
    {
        "Fach": "DEU",
        "Datum": "2025-02-12",
        "Lehrkraft": "Scheibe, Sophia",
        "Thema": "Wortarten: Wortarten unterscheiden",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 0,
        "Transferdenken": 1,
        "Basiswissen": 1,
        "Freitext": "Mia hat ihre Übungen vom letzen Mal weiter bearbeitet. Sie hat manchmal Probleme die Aufgabe richtig zu verstehen., Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, vorbereitet, Lernfortschritt erzielt, Basiswissen vorhanden, fähig zu Transferdenken"
    },
    {
        "Fach": "MAT",
        "Datum": "2025-02-07",
        "Lehrkraft": "Thiele, Dipl.-Ing. Olaf",
        "Thema": "weitere Themen: Korr. LK",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 0,
        "Transferdenken": 0,
        "Basiswissen": 1,
        "Freitext": "arbeitet sehr langsam / EME!, Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, vorbereitet, Lernfortschritt erzielt, Basiswissen vorhanden"
    },
    {
        "Fach": "DEU",
        "Datum": "2025-01-29",
        "Lehrkraft": "Scheibe, Sophia",
        "Thema": "Der Satz: Wörtliche Rede",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 0,
        "Transferdenken": 1,
        "Basiswissen": 1,
        "Freitext": "Mia hat Übungen zur wörtlichen Rede gemacht. Sie kam damit ganz gut zurecht. Zum Ende hin wurde sie etwas unkonzentriert., Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, vorbereitet, Lernfortschritt erzielt, Basiswissen vorhanden, fähig zu Transferdenken"
    },
    {
        "Fach": "MAT",
        "Datum": "2025-01-24",
        "Lehrkraft": "Reindel, Abby",
        "Thema": "Grundrechenarten: Halbschriftlich rechnen",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 0,
        "Transferdenken": 0,
        "Basiswissen": 0,
        "Freitext": "Mia hat heute sehr gut mitgemacht und war motiviert zu lernen. Wir haben das halbschriftliche Addieren und Subtrahieren geübt und Fragen geklärt. Am Ende haben wir noch Geometrie angefangen, dort viel es ihr allerdings schwer aufwendigere Figuren mit Diagonalen drin an der Spiegelachse zu spiegeln., beteiligt sich / gute Mitarbeit, Absprachen einhaltend, fleißig / bemüht, arbeitet selbstständig, konzentriert, vorbereitet, Lernfortschritt erzielt"
    },
    {
        "Fach": "DEU",
        "Datum": "2025-01-22",
        "Lehrkraft": "Scheibe, Sophia",
        "Thema": "Wortarten: Wortarten",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 0,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 0,
        "Transferdenken": 1,
        "Basiswissen": 1,
        "Freitext": "Mia schreibt wohl bald eine Leistungskontrolle in deutsch. Leider konnte sie mir nicht mehr sagen über welches Thema. Sie hatte auch keine Unterrichtsmaterialien mit in denen ich hätte nachschauen können. Wir haben Übungen zu Wortarten gemacht. Sie muss dazu aufgefordert werden, die Aufgabenstellung richtig zu lesen, ansonsten hat sie Probleme mit der Aufgabe., Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, konzentriert, Materialien fehlen, benötigt Aufforderung, Lernfortschritt erzielt, Basiswissen vorhanden, fähig zu Transferdenken"
    },
        {
        "Fach": "MAT",
        "Datum": "2025-01-10",
        "Lehrkraft": "Reindel, Abby",
        "Thema": "Rechengesetze und Regeln: Subtraktion",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 0,
        "Vorbereitet": 1,
        "Konzentriert": 0,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 1,
        "Transferdenken": 0,
        "Basiswissen": 0,
        "Freitext": "Mia schriebt nächste Woche einen Mathe-Test. Das direkte Thema konnte sie mir nicht sagen und auch ihre Unterrichtsübungen hatte sie nicht mit. Wir haben deswegen halbschriftliche Subtraktion geübt, weil sie das wohl gerade im Unterricht behandelt haben. Der Ablauf der Strategie halbschriftlich Rechnen ist ihr bekannt und wurde verinnerlicht. Subtrahieren mit Zehnerübertrag fällt ihr schwer und funktionierte nur mit meiner Hilfe. Mia lässt sich leicht ablenken und hat ein großes Mitteilungsbedürfnis, weswegen nicht viele Aufgaben geschafft werden, dennoch beim gemeinsamen Arbeiten aufmerksam mitmacht., Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, benötigt Aufforderung, unkonzentriert, vorbereitet, Lernfortschritt erzielt, beherrscht Thema"
    },
    {
        "Fach": "DEU",
        "Datum": "2025-01-08",
        "Lehrkraft": "Scheibe, Sophia",
        "Thema": "Wortbildung: neue Wörter bilden",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 0,
        "Transferdenken": 1,
        "Basiswissen": 1,
        "Freitext": "Mia schreibt bald eine Arbeit über Wortbausteine (nach eigener Aussage), weshalb wir Übungen zur Wortbildung gemacht haben. Sie kam damit relativ gut zurecht und hat die meiste Zeit selbstständig gearbeitet., Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, vorbereitet, benötigt Aufforderung, Lernfortschritt erzielt, Basiswissen vorhanden, fähig zu Transferdenken"
    },
        {
        "Fach": "DEU",
        "Datum": "2024-12-06",
        "Lehrkraft": "Reindel, Abby",
        "Thema": "weitere Themen: Rechtschreibung",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 0,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 0,
        "Transferdenken": 0,
        "Basiswissen": 1,
        "Freitext": "Mia lässt sich sehr leicht ablenken. Ist sie in ihrer Arbeitsphase drin arbeitet die gewissenhaft. Sie hat heute die Rechtschreibung von den Auslauten b/p geübt und anschließend mit Merkwörtern gefestigt, Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, Basiswissen vorhanden, Unverständnis, Lernfortschritt erzielt"
    },
    {
        "Fach": "MAT",
        "Datum": "2024-12-04",
        "Lehrkraft": "Scheibe, Sophia",
        "Thema": "Zahlen darstellen: Zahlenstrahl, Nachbarzahlen",
        "Absprachen": 1,
        "Mitarbeit": 1,
        "Fleißig": 1,
        "Selbstständig": 1,
        "Vorbereitet": 1,
        "Konzentriert": 1,
        "Lernfortschritt": 1,
        "Beherrscht Thema": 0,
        "Transferdenken": 1,
        "Basiswissen": 1,
        "Freitext": "Mia ist eine aufgeschlossene, nette Schülerin. Sie hat ihre Aufgaben selbstständig und größtenteils konzentriert bearbeitet. Bei Fragen kommt sie auf mich zu. Sie hat heute eine 1 in Mathe bekommen., Absprachen einhaltend, beteiligt sich / gute Mitarbeit, fleißig / bemüht, arbeitet selbstständig, konzentriert, vorbereitet, Lernfortschritt erzielt, Basiswissen vorhanden, fähig zu Transferdenken"
    },
]

bewertungen_df = pd.DataFrame(bewertungen_data, columns=bewertungs_columns)

# Ausgabe der DataFrames
print("Schülerdaten:")
print(schueler_df)
print("\nBewertungsdaten:")
print(bewertungen_df)
